/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import config.Usersession;
import config.koneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YOGI
 */
public class CRUD_DataRM extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_obat
     */
    String level = Usersession.getLevel();

    public CRUD_DataRM() {
        initComponents();
        tampildata();
        tanggal();
        tampildaerah();

    }
    Statement st;
    Connection con = koneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tnamapasien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tnoidentitas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        talamat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tnorm = new javax.swing.JTextField();
        tkodeanggota = new javax.swing.JTextField();
        talamatktp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tnotelepon = new javax.swing.JTextField();
        cbjeniskelamin = new javax.swing.JComboBox<>();
        ttanggallahir = new com.toedter.calendar.JDateChooser();
        btnhapus = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ttanggal = new javax.swing.JTextField();
        cbdaerah = new javax.swing.JComboBox<>();
        tiddaerahrm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btncetakkunjungan2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nama Pasien");

        tnamapasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnamapasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamapasienActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Jenis Kelamin");

        btnsimpan.setBackground(new java.awt.Color(51, 51, 255));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("No Identitas");

        tnoidentitas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnoidentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnoidentitasActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Alamat KTP");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tanggal Lahir");

        talamat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Alamat");

        btnupdate.setBackground(new java.awt.Color(255, 102, 51));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UBAH");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("No RM");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Kode Anggota");

        tnorm.setEditable(false);
        tnorm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tkodeanggota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tkodeanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkodeanggotaActionPerformed(evt);
            }
        });

        talamatktp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("NO Telepon");

        tnotelepon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cbjeniskelamin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbjeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        cbjeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjeniskelaminActionPerformed(evt);
            }
        });

        ttanggallahir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(ttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel12))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(talamatktp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tkodeanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tnorm, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tnoidentitas))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(39, 39, 39)
                                            .addComponent(tnotelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 7, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnorm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tkodeanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(talamatktp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnoidentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnotelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 360, 460));

        tCari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        getContentPane().add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 710, 40));

        tblpasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 900, 370));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KELOLA DATA REKAM MEDIS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 530, 40));

        btnrefresh.setBackground(new java.awt.Color(51, 51, 255));
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh form");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 160, 48));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 80, 30));

        ttanggal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(ttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 170, 30));

        cbdaerah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbdaerah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIlih Daerah" }));
        cbdaerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdaerahActionPerformed(evt);
            }
        });
        getContentPane().add(cbdaerah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 143, 230, 40));

        tiddaerahrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tiddaerahrm.setForeground(new java.awt.Color(255, 255, 255));
        tiddaerahrm.setText("~");
        getContentPane().add(tiddaerahrm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 20, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari Pasien");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 150, 40));

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, 40));

        btncetakkunjungan2.setBackground(new java.awt.Color(51, 153, 255));
        btncetakkunjungan2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncetakkunjungan2.setText("CETAK DATA PEMERIKSAAN");
        btncetakkunjungan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakkunjungan2ActionPerformed(evt);
            }
        });
        getContentPane().add(btncetakkunjungan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 240, 50));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BG-pembayaran.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        tampildata();
    }//GEN-LAST:event_tCariActionPerformed

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        tampildata();
    }//GEN-LAST:event_tCariKeyReleased

    private void tblpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpasienMouseClicked
        int i = tblpasien.getSelectedRow();
        tnorm.setText(model.getValueAt(i, 0).toString());
        tkodeanggota.setText(model.getValueAt(i, 2).toString());
        tnamapasien.setText(model.getValueAt(i, 3).toString());
        talamat.setText(model.getValueAt(i, 4).toString());
        talamatktp.setText(model.getValueAt(i, 5).toString());
        cbjeniskelamin.setSelectedItem(model.getValueAt(i, 6).toString());
        tnoidentitas.setText(model.getValueAt(i, 7).toString());
        tnotelepon.setText(model.getValueAt(i, 9).toString());


    }//GEN-LAST:event_tblpasienMouseClicked

    private void tnamapasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamapasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamapasienActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String iddaerah = tiddaerahrm.getText();
        String nomorrm = tnorm.getText();
        String kodeanggota = tkodeanggota.getText();
        String koderm = iddaerah + "-" + nomorrm + "-" + kodeanggota;
        String namarm = tnamapasien.getText();
        String alamatrm = talamat.getText();
        String jk = cbjeniskelamin.getSelectedItem().toString();
        String noidentitas = tnoidentitas.getText();
        String tglahir = df.format(ttanggallahir.getDate());
        String alamatktp = talamatktp.getText();
        String notelp = tnotelepon.getText();

        if (namarm.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukan Nama Terlebih Dahulu !!");
        } else {
            try {
                con.createStatement().executeUpdate("insert into tbl_rm values("
                        + "'" + iddaerah + "','" + nomorrm + "','" + kodeanggota + "','" + koderm + "','" + namarm + "',"
                        + "'" + alamatrm + "','" + jk + "','" + noidentitas + "','" + tglahir + "','" + alamatktp + "','" + notelp + "')");
                JOptionPane.showMessageDialog(null, "Berhasil !!");
                Resetform();

            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Gagal !!" + e);

            }
        }


    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String iddaerah = tiddaerahrm.getText();
        String nomorrm = tnorm.getText();
        String kodeanggota = tkodeanggota.getText();
        String koderm = iddaerah + "-" + nomorrm + "-" + kodeanggota;
        String namarm = tnamapasien.getText();
        String alamatrm = talamat.getText();
        String jk = cbjeniskelamin.getSelectedItem().toString();
        String noidentitas = tnoidentitas.getText();
        String tglahir = df.format(ttanggallahir.getDate());
        String alamatktp = talamatktp.getText();
        String notelp = tnotelepon.getText();;

        try {
            con.createStatement().executeUpdate("update tbl_rm set kode_daerah='" + iddaerah + "',kode_anggota='" + kodeanggota + "',nama_pasien='" + namarm + "',"
                    + "alamat='" + alamatrm + "',jenis_kelamin='" + jk + "',no_identitas='" + noidentitas + "',tanggal_lahir='" + tglahir + "',"
                    + "alamat_ktp='" + alamatktp + "',no_telepon='" + notelp + "' where kode_rm ='" + model.getValueAt(tblpasien.getSelectedRow(), 1).toString() + "'");
            JOptionPane.showMessageDialog(null, "Berhasill !! ");
            Resetform();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "gagal !! " + e);
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        Resetform();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void tnoidentitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnoidentitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnoidentitasActionPerformed

    private void cbdaerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdaerahActionPerformed
        String daerah = cbdaerah.getSelectedItem().toString();
        String sql = "SELECT * FROM tbl_daerah where nama_daerah='" + daerah + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String kodedaerah = rs.getString("kode_daerah");
                tiddaerahrm.setText(kodedaerah);
                NORMAUTO();
                tampildata();

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cbdaerahActionPerformed

    private void tkodeanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkodeanggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkodeanggotaActionPerformed

    private void cbjeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjeniskelaminActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int keputusan = JOptionPane.showConfirmDialog(this, "apakah anda yakinmenghapus data ini? ");
        switch (keputusan) {
            case JOptionPane.YES_OPTION:
                String rm = model.getValueAt(tblpasien.getSelectedRow(), 1).toString();
                try {
                    con.createStatement().executeUpdate("delete from tbl_rm where kode_rm='" + rm + "'");
                    JOptionPane.showMessageDialog(null, "Berhasil Menghapus !!");
                    Resetform();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal !! " + e);
                }
        }

    }//GEN-LAST:event_btnhapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btncetakkunjungan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakkunjungan2ActionPerformed
        try {
            cetakperpasien();
        } catch (JRException ex) {
            Logger.getLogger(Laporan_pelayanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncetakkunjungan2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_DataRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_DataRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_DataRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_DataRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_DataRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btncetakkunjungan2;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbdaerah;
    private javax.swing.JComboBox<String> cbjeniskelamin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField talamatktp;
    private javax.swing.JTable tblpasien;
    private javax.swing.JLabel tiddaerahrm;
    private javax.swing.JTextField tkodeanggota;
    private javax.swing.JTextField tnamapasien;
    private javax.swing.JTextField tnoidentitas;
    private javax.swing.JTextField tnorm;
    private javax.swing.JTextField tnotelepon;
    private javax.swing.JTextField ttanggal;
    private com.toedter.calendar.JDateChooser ttanggallahir;
    // End of variables declaration//GEN-END:variables
public void tampildata() {
        String[] judul = {"NO RM", "Kode RM", "Anggota", "Nama Pasien", "Alamat", "Alamat KTP", "JK", "Identitas", "Lahir", "Telepon"};
        model = new DefaultTableModel(judul, 0);
        tblpasien.setModel(model);
        lebarkolom();
        String sql = "SELECT *, tbl_daerah.*, tbl_rm.* from tbl_rm"
                + " inner join tbl_daerah on tbl_daerah.kode_daerah = tbl_rm.kode_daerah"
                + " where nama_daerah='" + cbdaerah.getSelectedItem().toString() + "' and "
                + " (kode_rm like '%" + tCari.getText() + "%' or nama_pasien like'%" + tCari.getText() + "%')"
                + " ORDER BY no_rm ASC";

        try {
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {

                String norm = rs.getString("no_rm");
                String koderm = rs.getString("kode_rm");
                String anggota = rs.getString("kode_anggota");
                String nama = rs.getString("nama_pasien");
                String alamatktp = rs.getString("alamat_ktp");
                String jk = rs.getString("jenis_kelamin");
                String alamat = rs.getString("alamat");
                String identitas = rs.getString("no_identitas");
                String lahir = rs.getString("tanggal_lahir");
                String telepon = rs.getString("no_telepon");
                String[] data = {norm, koderm, anggota, nama, alamat, alamatktp, jk, identitas, lahir, telepon};
                model.addRow(data);

            }
        } catch (Exception e) {
            System.out.println(e);

        }
    }

    public void Resetform() {

        tnamapasien.setText("");
        tnoidentitas.setText("");
        tnorm.setText("");
        tkodeanggota.setText("");
        talamat.setText("");
        talamatktp.setText("");
        tnotelepon.setText("");
        tampildata();

    }

    public void tanggal() {

        Calendar kal = new GregorianCalendar();
        int tahun = kal.get(Calendar.YEAR);
        int bulan = kal.get(Calendar.MONTH) + 1;
        int hari = kal.get(Calendar.DAY_OF_MONTH);

        if (bulan < 10) {
            String tanggal = tahun + "-0" + bulan + "-" + hari;
            ttanggal.setText(tanggal);
        } else {
            String tanggal = tahun + "-" + bulan + "-" + hari;

            ttanggal.setText(tanggal);
        }
    }

    public void lebarkolom() {
        TableColumn column;
        for (int i = 0; i < 8; i++) {
            column = tblpasien.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(75);
            } else if (i == 1) {
                column.setPreferredWidth(50);
            } else if (i == 2) {
                column.setPreferredWidth(35);
            } else if (i == 3) {
                column.setPreferredWidth(130);
            } else if (i == 4) {
                column.setPreferredWidth(100);
            } else if (i == 6) {
                column.setPreferredWidth(15);

            }
        }
    }

    public void NORMAUTO() {
        String iddaerah = tiddaerahrm.getText();
        String sql = "select max(left(no_rm,5)) from tbl_rm where kode_daerah='" + iddaerah + "'";

        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    tnorm.setText("000001");

                } else {
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                    if (autoid <= 9) {
                        tnorm.setText("00000" + autoid);
                    } else if (autoid > 9 && autoid <= 99) {
                        tnorm.setText("0000" + autoid);
                    } else if (autoid > 99 && autoid <= 999) {
                        tnorm.setText("000" + autoid);
                    } else if (autoid > 999 && autoid <= 9999) {
                        tnorm.setText("00" + autoid);
                    } else if (autoid > 9999) {
                        tnorm.setText("0" + autoid);
                    }
                }

            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "NO RM Gagal dibuat !! " + e);
        }

    }

    public void tampildaerah() {
        String sql = "SELECT * from tbl_daerah";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String daerah = rs.getString("nama_daerah");

                cbdaerah.addItem(daerah);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
      public void cetakperpasien() throws JRException {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

        
        String pasien = model.getValueAt(tblpasien.getSelectedRow(), 1).toString();
        JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/laporan/laporanpelayanan2.jrxml"));
        JRDesignQuery query = new JRDesignQuery();
        HashMap param = new HashMap();
        param.put("koderm", pasien);
        query.setText("select *, tbl_rm.* from tbl_datasakit"
                + " inner join tbl_rm using(kode_rm)"
                + " where kode_rm='" + pasien + "'");
        jd.setQuery(query);
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
        JasperViewer.viewReport(jp, false);
    }
}
