/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.koneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YOGI
 */
public class CRUD_lain extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_lain
     */
    public CRUD_lain() {
        initComponents();
        tabelivisitedokter();
        tanggal();
    }
    Statement st;
    Connection con = koneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;
    DefaultTableModel modelobat;
    DefaultTableModel modellist;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ttanggal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnlain = new javax.swing.JButton();
        btntablet = new javax.swing.JButton();
        btncairan = new javax.swing.JButton();
        btninjeksi = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblinjeksi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cbshift = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        tnamapasien = new javax.swing.JTextField();
        tidpendaftaran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnhapusvisitedokter = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ttanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 70, 30));

        btnlain.setBackground(new java.awt.Color(0, 204, 102));
        btnlain.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btnlain.setText("+ Visite Dokter");
        btnlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlainActionPerformed(evt);
            }
        });
        getContentPane().add(btnlain, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 80, 140, 40));

        btntablet.setBackground(new java.awt.Color(0, 102, 204));
        btntablet.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btntablet.setForeground(new java.awt.Color(255, 255, 255));
        btntablet.setText("+ Oral");
        btntablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntabletActionPerformed(evt);
            }
        });
        getContentPane().add(btntablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, 130, 40));

        btncairan.setBackground(new java.awt.Color(255, 255, 153));
        btncairan.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btncairan.setText("+ Injeksi&Cairan");
        btncairan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncairanActionPerformed(evt);
            }
        });
        getContentPane().add(btncairan, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 150, 40));

        btninjeksi.setBackground(new java.awt.Color(0, 153, 204));
        btninjeksi.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btninjeksi.setForeground(new java.awt.Color(255, 255, 255));
        btninjeksi.setText("+ Alkes");
        btninjeksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninjeksiActionPerformed(evt);
            }
        });
        getContentPane().add(btninjeksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 110, 40));

        btnkembali.setBackground(new java.awt.Color(51, 51, 255));
        btnkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("Daftar Pasien");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 150, 40));

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("* Tabel Visite Dokter");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 240, 30));

        tblinjeksi.setBorder(new javax.swing.border.MatteBorder(null));
        tblinjeksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblinjeksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblinjeksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 710, 380));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbshift.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbshift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi", "Siang", "Malam" }));
        cbshift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbshiftActionPerformed(evt);
            }
        });
        jPanel1.add(cbshift, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 200, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Shift");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 360, 70));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsimpan.setBackground(new java.awt.Color(0, 51, 204));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("* Tambah Visite Dokter");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 360, 360));

        tnamapasien.setEditable(false);
        tnamapasien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(tnamapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 330, 35));

        tidpendaftaran.setEditable(false);
        tidpendaftaran.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tidpendaftaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tidpendaftaranKeyReleased(evt);
            }
        });
        getContentPane().add(tidpendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 218, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Pendaftaran");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Pasien");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        btnhapusvisitedokter.setBackground(new java.awt.Color(255, 51, 51));
        btnhapusvisitedokter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhapusvisitedokter.setForeground(new java.awt.Color(255, 255, 255));
        btnhapusvisitedokter.setText("Hapus");
        btnhapusvisitedokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusvisitedokterActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapusvisitedokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, 140, 40));

        jButton2.setBackground(new java.awt.Color(0, 51, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Refresh Form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, 140, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-CRUD_1.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlainActionPerformed
        CRUD_lain lb = new CRUD_lain();
        lb.tidpendaftaran.setText(tidpendaftaran.getText());
        lb.tnamapasien.setText(tnamapasien.getText());
        lb.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlainActionPerformed

    private void btntabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntabletActionPerformed
        CRUD_tablet lb = new CRUD_tablet();
        lb.tidpendaftaran.setText(tidpendaftaran.getText());
        lb.tnamapasien.setText(tnamapasien.getText());
        lb.tabelinjeksi();
        lb.setVisible(true);
        dispose();
    }//GEN-LAST:event_btntabletActionPerformed

    private void btncairanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncairanActionPerformed
        CRUD_cairan lb = new CRUD_cairan();
        lb.tidpendaftaran.setText(tidpendaftaran.getText());
        lb.tnamapasien.setText(tnamapasien.getText());
        lb.setVisible(true);
        dispose();

    }//GEN-LAST:event_btncairanActionPerformed

    private void btninjeksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninjeksiActionPerformed
        CRUD_alkes lb = new CRUD_alkes();
        lb.tidpendaftaran.setText(tidpendaftaran.getText());
        lb.tnamapasien.setText(tnamapasien.getText());
        lb.setVisible(true);
        dispose();
    }//GEN-LAST:event_btninjeksiActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        new daftar_pasienRI().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void cbshiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbshiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbshiftActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        String idpendaftaran = tidpendaftaran.getText();
        String tanggal = ttanggal.getText();
        String shift = cbshift.getSelectedItem().toString();
        try {
            con.createStatement().executeUpdate("insert into tbl_rivisitedokter values('" + idpendaftaran + "','" + tanggal + "','" + shift + "')");
            JOptionPane.showMessageDialog(null, "Berhasil  !!");
            tabelivisitedokter();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal !! " + e);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void tidpendaftaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidpendaftaranKeyReleased
        tabelivisitedokter();
    }//GEN-LAST:event_tidpendaftaranKeyReleased

    private void btnhapusvisitedokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusvisitedokterActionPerformed
        int i = tblinjeksi.getSelectedRow();
        String idpendaftaran = model.getValueAt(i, 0).toString();
        String tanggal = model.getValueAt(i, 1).toString();
        String shift = model.getValueAt(i, 2).toString();

        try {
            con.createStatement().executeUpdate("delete from tbl_rivisitedokter "
                    + "where id_pendaftaran='" + idpendaftaran + "' and shift='" + shift + "' and tanggal='" + tanggal + "'");
            JOptionPane.showMessageDialog(null, "Berhasil !!");
            resetform();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "gagal !! " + e);
        }
    }//GEN-LAST:event_btnhapusvisitedokterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resetform();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_lain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btncairan;
    private javax.swing.JButton btnhapusvisitedokter;
    private javax.swing.JButton btninjeksi;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnlain;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntablet;
    private javax.swing.JComboBox<String> cbshift;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblinjeksi;
    public javax.swing.JTextField tidpendaftaran;
    public javax.swing.JTextField tnamapasien;
    private javax.swing.JTextField ttanggal;
    // End of variables declaration//GEN-END:variables

    public void tabelivisitedokter() {
        String[] judul = {"ID Pendaftaran", "Tanggal", "Shift"};
        model = new DefaultTableModel(judul, 0);
        tblinjeksi.setModel(model);
        String sql = "SELECT * from tbl_rivisitedokter where id_pendaftaran='" + tidpendaftaran.getText() + "'";

        try {
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {
                String id = rs.getString("id_pendaftaran");

                String tgl = rs.getString("tanggal");
                String shift = rs.getString("shift");

                String[] data = {id, tgl, shift};
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);

        }
    }

    private void resetform() {

        tabelivisitedokter();

    }

    public void tanggal() {

        Calendar kal = new GregorianCalendar();
        int tahun = kal.get(Calendar.YEAR);
        int bulan = kal.get(Calendar.MONTH) + 1;
        int hari = kal.get(Calendar.DAY_OF_MONTH);

        if (bulan < 10) {
            String tanggal = tahun + "-0" + bulan + "-" + hari;
            ttanggal.setText(tanggal);
        } else {
            String tanggal = tahun + "-" + bulan + "-" + hari;

            ttanggal.setText(tanggal);
        }
    }
}
