/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Usersession;
import config.koneksiDB;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YOGI
 */
public class CRUD_pasien extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_pasien
     */
    String level = Usersession.getLevel();
    String user = Usersession.getNama();

    public CRUD_pasien() {
        initComponents();
//        tabelpasien();
        lebarKolom();
        tampildaerah();
        tabelpasien();
        tampilpetugas();
        tanggal();

        tnopendaftaran.setText("auto fill");
        tnopendaftaran.setEnabled(false);
        ttanggal.setEnabled(false);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        tnorm.setEnabled(false);

    }
    Statement st;
    Connection con = koneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formRM = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbdaerahRM = new javax.swing.JComboBox<>();
        tnorm = new javax.swing.JTextField();
        tkodeanggota = new javax.swing.JTextField();
        tnamarm = new javax.swing.JTextField();
        talamatrm = new javax.swing.JTextField();
        cbjeniskelaminrm = new javax.swing.JComboBox<>();
        tnoidentitasrm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        talamatktprm = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tgllahirrm = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        tnotelepomrm = new javax.swing.JTextField();
        btnsimpandatarm = new javax.swing.JButton();
        tiddaerahrm = new javax.swing.JLabel();
        btnupdateRM = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnopendaftaran = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        ttanggal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tnomorrmpasien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        talamat = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tusia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbpoli = new javax.swing.JComboBox<>();
        cbkriteria = new javax.swing.JComboBox<>();
        cbjeniskunjungan = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cbpetugas = new javax.swing.JComboBox<>();
        btnhapus = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnkembali = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbdaerah = new javax.swing.JComboBox<>();
        btntambahRM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        btnupdate = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        tidpendaftaran = new javax.swing.JLabel();

        formRM.setMinimumSize(new java.awt.Dimension(1030, 600));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAMBAH DATA RM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Anggota");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kode Daerah");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nomor RM");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Alamat KTP");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("No Identitas /BPjS");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Jenis Kelamin");

        cbdaerahRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbdaerahRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIlih Daerah" }));
        cbdaerahRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdaerahRMActionPerformed(evt);
            }
        });

        tnorm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnormActionPerformed(evt);
            }
        });

        tkodeanggota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tnamarm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        talamatrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cbjeniskelaminrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbjeniskelaminrm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        cbjeniskelaminrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjeniskelaminrmActionPerformed(evt);
            }
        });

        tnoidentitasrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Alamat");

        talamatktprm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tanggal Lahir");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("No Telepon");

        tnotelepomrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnsimpandatarm.setBackground(new java.awt.Color(51, 0, 255));
        btnsimpandatarm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsimpandatarm.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpandatarm.setText("Simpan");
        btnsimpandatarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpandatarmActionPerformed(evt);
            }
        });

        tiddaerahrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tiddaerahrm.setForeground(new java.awt.Color(255, 255, 255));
        tiddaerahrm.setText("~");

        btnupdateRM.setBackground(new java.awt.Color(102, 204, 0));
        btnupdateRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdateRM.setForeground(new java.awt.Color(255, 255, 255));
        btnupdateRM.setText("UPDATE");
        btnupdateRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateRMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tkodeanggota)
                        .addComponent(talamatrm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbdaerahRM, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tiddaerahrm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tnoidentitasrm, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(tgllahirrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnsimpandatarm, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnupdateRM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tnamarm)
                    .addComponent(cbjeniskelaminrm, javax.swing.GroupLayout.Alignment.TRAILING, 0, 217, Short.MAX_VALUE)
                    .addComponent(talamatktprm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(tnotelepomrm, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(tnorm))
                .addGap(69, 69, 69))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tnorm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnamarm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(talamatktprm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbdaerahRM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiddaerahrm))
                        .addGap(26, 26, 26)
                        .addComponent(tkodeanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(talamatrm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbjeniskelaminrm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnoidentitasrm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgllahirrm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tnotelepomrm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsimpandatarm, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnupdateRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout formRMLayout = new javax.swing.GroupLayout(formRM.getContentPane());
        formRM.getContentPane().setLayout(formRMLayout);
        formRMLayout.setHorizontalGroup(
            formRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formRMLayout.setVerticalGroup(
            formRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formRMLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("No Pendaftaran");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("* Nama");

        tnopendaftaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnopendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnopendaftaranActionPerformed(evt);
            }
        });

        tnama.setEditable(false);
        tnama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(51, 51, 255));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("+ PASIEN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(51, 204, 0));
        btnbatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal.setText("REFRESH");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        ttanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ttanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttanggalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tanggal");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("* Nomor RM");

        tnomorrmpasien.setEditable(false);
        tnomorrmpasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("* Alamat");

        talamat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("* Usia");

        tusia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("* Pilih Poli");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("* Krit. Kunjungan");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("* Jenis Kunjungan");

        cbpoli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbpoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poli Umum", "Poli Gigi", "Poli BP", "Poli KIA", "Poli Fisioterapi" }));

        cbkriteria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbkriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anak", "Dewasa", "KB", "ANC", "Gigi", "Fisioterapi" }));

        cbjeniskunjungan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbjeniskunjungan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baru", "Lama" }));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("* Petugas Periksa");

        cbpetugas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbpetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokter Umum", "Dokter Gigi", "Dokter SpOG", "Bidan", "Perawat", "Terapis" }));

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(cbpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tnopendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(29, 29, 29)
                                .addComponent(ttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbpoli, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tnomorrmpasien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(talamat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbkriteria, javax.swing.GroupLayout.Alignment.LEADING, 0, 193, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tnama, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(tusia)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbjeniskunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnopendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbpoli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbkriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbjeniskunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tusia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tnomorrmpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 640, 470));

        tCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        getContentPane().add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 360, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TAMBAH PASIEN +");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 220, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("REGISTER RAWAT JALAN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 460, 40));

        btnkembali.setBackground(new java.awt.Color(51, 51, 255));
        btnkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("DASHBOARD");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 170, 50));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset No Pendaftaran");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 133, 180, 40));

        cbdaerah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbdaerah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Daerah" }));
        cbdaerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdaerahActionPerformed(evt);
            }
        });
        getContentPane().add(cbdaerah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 220, 40));

        btntambahRM.setBackground(new java.awt.Color(0, 153, 204));
        btntambahRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntambahRM.setForeground(new java.awt.Color(255, 255, 255));
        btntambahRM.setText("Data RM Baru");
        btntambahRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahRMActionPerformed(evt);
            }
        });
        getContentPane().add(btntambahRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 130, 50));

        tblpasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 610, 470));

        btnupdate.setBackground(new java.awt.Color(0, 153, 153));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 113, 47));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BG-pembayaran.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tidpendaftaran.setText("I-000001");
        getContentPane().add(tidpendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed

    }//GEN-LAST:event_tCariActionPerformed

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        String[] judul = {"NO RM", "Kode RM", "Nama Pasien", "Jenis Kelamin", "Alamat"};
        model = new DefaultTableModel(judul, 0);
        tblpasien.setModel(model);
        lebarKolom();
        String sql = "SELECT *, tbl_daerah.*, tbl_rm.* from tbl_rm"
                + " inner join tbl_daerah on tbl_daerah.kode_daerah = tbl_rm.kode_daerah"
                + " where nama_daerah='" + cbdaerah.getSelectedItem().toString() + "' and nama_pasien like '%" + tCari.getText() + "%' "
                + " ORDER BY no_rm ASC ";

        try {
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {
                String norm = rs.getString("no_rm");
                String koderm = rs.getString("kode_rm");
                String nama = rs.getString("nama_pasien");
                String jk = rs.getString("jenis_kelamin");
                String alamat = rs.getString("alamat");

                String[] data = {norm, koderm, nama, jk, alamat};
                model.addRow(data);

            }
        } catch (Exception e) {
            System.out.println(e);

        }

    }//GEN-LAST:event_tCariKeyReleased

    private void tnopendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnopendaftaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnopendaftaranActionPerformed

    private void tnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        simpanpelayanan();
//        try {
//            cetakperpasien();
//            Resetform();
//        } catch (JRException ex) {
//            Logger.getLogger(CRUD_pasien.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        Resetform();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        switch (level) {
            case "admin": {

                dashboard dsb = new dashboard();
                dsb.dashAdmin();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "receptionist": {

                dashboard dsb = new dashboard();
                dsb.dashReceptionist();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "dokter": {

                dashboard dsb = new dashboard();
                dsb.dashDokter();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "apoteker": {

                dashboard dsb = new dashboard();
                dsb.dashApoteker();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            default:
                break;
        }

    }//GEN-LAST:event_btnkembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int reset = JOptionPane.showConfirmDialog(this, "Apakah Benar-Benar ingin melakukan reset pendaftaran?");
        switch (reset) {
            case JOptionPane.YES_OPTION:
                try {
                    con.createStatement().executeUpdate("delete from tbl_pendaftaran");
                    JOptionPane.showMessageDialog(null, "Berhasil!!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ttanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttanggalActionPerformed

    private void cbdaerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdaerahActionPerformed
        tabelpasien();
    }//GEN-LAST:event_cbdaerahActionPerformed

    private void btntambahRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahRMActionPerformed
        new CRUD_DataRM().setVisible(true);
    }//GEN-LAST:event_btntambahRMActionPerformed

    private void btnsimpandatarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpandatarmActionPerformed
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String iddaerah = tiddaerahrm.getText();
        String nomorrm = tnorm.getText();
        String kodeanggota = tkodeanggota.getText();
        String koderm = iddaerah + "-" + nomorrm + "-" + kodeanggota;
        String namarm = tnamarm.getText();
        String alamatrm = talamatrm.getText();
        String jk = cbjeniskelaminrm.getSelectedItem().toString();
        String noidentitas = tnoidentitasrm.getText();
        String tglahir = df.format(tgllahirrm.getDate());
        String alamatktp = talamatktprm.getText();
        String notelp = tnotelepomrm.getText();

        if (namarm.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukan Nama Terlebih Dahulu !!");
        } else {
            try {
                con.createStatement().executeUpdate("insert into tbl_rm values("
                        + "'" + iddaerah + "','" + nomorrm + "','" + kodeanggota + "','" + koderm + "','" + namarm + "',"
                        + "'" + alamatrm + "','" + jk + "','" + noidentitas + "','" + tglahir + "','" + alamatktp + "','" + notelp + "')");
                JOptionPane.showMessageDialog(null, "Berhasil !!");
                Resetform();
                formRM.dispose();
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Gagal !!" + e);

            }
        }

    }//GEN-LAST:event_btnsimpandatarmActionPerformed

    private void tnormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnormActionPerformed

    private void cbdaerahRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdaerahRMActionPerformed
        String daerah = cbdaerahRM.getSelectedItem().toString();
        String sql = "SELECT * FROM tbl_daerah where nama_daerah='" + daerah + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String kodedaerah = rs.getString("kode_daerah");
                tiddaerahrm.setText(kodedaerah);
                NORMAUTO();

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cbdaerahRMActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int keputusan = JOptionPane.showConfirmDialog(this, "apakah anda yakinmenghapus data ini? ");
        switch (keputusan) {
            case JOptionPane.YES_OPTION:
                String rm = tnomorrmpasien.getText();
                try {
                    con.createStatement().executeUpdate("delete from tbl_rm where kode_rm='" + rm + "'");
                    JOptionPane.showMessageDialog(null, "Berhasil Menghapus !!");
                    Resetform();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal !! " + e);
                }
        }

    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        formRM.setVisible(true);
        btnsimpandatarm.setEnabled(false);
        tnorm.setEnabled(false);
        btnupdateRM.setEnabled(true);
        String rm = tnomorrmpasien.getText();
        String nama = tnama.getText();
        String sql = "Select * from tbl_rm where kode_rm='" + rm + "'";

        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String daerah = rs.getString("kode_daerah");
                String kodeanggota = rs.getString("kode_anggota");
                String alamat = rs.getString("alamat");
                String alamat_ktp = rs.getString("alamat_ktp");
                String identitas = rs.getString("no_identitas");
                String jk = rs.getString("jenis_kelamin");
                String no_telep = rs.getString("no_telepon");

                tiddaerahrm.setText(daerah);
                tnorm.setText(rm);
                tkodeanggota.setText(kodeanggota);
                tnamarm.setText(nama);
                talamatrm.setText(alamat);
                cbjeniskelaminrm.setSelectedItem(jk);
                tnoidentitasrm.setText(identitas);
                talamatktprm.setText(alamat_ktp);
                tnotelepomrm.setText(no_telep);

            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "gagal !! " + e);
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnupdateRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateRMActionPerformed
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String iddaerah = tiddaerahrm.getText();
        String nomorrm = tnorm.getText();
        String kodeanggota = tkodeanggota.getText();
        String koderm = iddaerah + "-" + nomorrm + "-" + kodeanggota;
        String namarm = tnamarm.getText();
        String alamatrm = talamatrm.getText();
        String jk = cbjeniskelaminrm.getSelectedItem().toString();
        String noidentitas = tnoidentitasrm.getText();
        String tglahir = df.format(tgllahirrm.getDate());
        String alamatktp = talamatktprm.getText();
        String notelp = tnotelepomrm.getText();

        try {
            con.createStatement().executeUpdate("update tbl_rm set kode_daerah='" + iddaerah + "',kode_anggota='" + kodeanggota + "',nama_pasien='" + namarm + "',"
                    + "alamat='" + alamatrm + "',jenis_kelamin='" + jk + "',no_identitas='" + noidentitas + "',tanggal_lahir='" + tglahir + "',"
                    + "alamat_ktp='" + alamatktp + "',no_telepon='" + notelp + "' where kode_rm ='" + nomorrm + "'");
            JOptionPane.showMessageDialog(null, "Berhasill !! ");
            formRM.dispose();
            Resetform();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "gagal !! " + e);
        }

    }//GEN-LAST:event_btnupdateRMActionPerformed

    private void cbjeniskelaminrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjeniskelaminrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjeniskelaminrmActionPerformed

    private void tblpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpasienMouseClicked
        int i = tblpasien.getSelectedRow();
        tnorm.setText(model.getValueAt(i, 0).toString());
        tnomorrmpasien.setText(model.getValueAt(i, 1).toString());
        tnama.setText(model.getValueAt(i, 2).toString());
        talamat.setText(model.getValueAt(i, 4).toString());
        talamatrm.setText(model.getValueAt(i, 4).toString());
        btnhapus.setEnabled(true);
        btnupdate.setEnabled(true);
        String sql = "Select left(tanggal_lahir,4) from tbl_rm where kode_rm='" + model.getValueAt(i, 1).toString() + "'";

        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                int tgllahir = rs.getInt(1);
                Calendar kal = new GregorianCalendar();
                int tahun = kal.get(Calendar.YEAR);

                int usia = tahun - tgllahir;
                tusia.setText(String.valueOf(usia));

            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_tblpasienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnsimpandatarm;
    private javax.swing.JButton btntambahRM;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdateRM;
    private javax.swing.JComboBox<String> cbdaerah;
    private javax.swing.JComboBox<String> cbdaerahRM;
    private javax.swing.JComboBox<String> cbjeniskelaminrm;
    private javax.swing.JComboBox<String> cbjeniskunjungan;
    private javax.swing.JComboBox<String> cbkriteria;
    private javax.swing.JComboBox<String> cbpetugas;
    private javax.swing.JComboBox<String> cbpoli;
    public javax.swing.JFrame formRM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField talamatktprm;
    private javax.swing.JTextField talamatrm;
    private javax.swing.JTable tblpasien;
    private com.toedter.calendar.JDateChooser tgllahirrm;
    private javax.swing.JLabel tiddaerahrm;
    private javax.swing.JLabel tidpendaftaran;
    private javax.swing.JTextField tkodeanggota;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnamarm;
    private javax.swing.JTextField tnoidentitasrm;
    private javax.swing.JTextField tnomorrmpasien;
    private javax.swing.JTextField tnopendaftaran;
    public javax.swing.JTextField tnorm;
    private javax.swing.JTextField tnotelepomrm;
    private javax.swing.JTextField ttanggal;
    private javax.swing.JTextField tusia;
    // End of variables declaration//GEN-END:variables
public void tabelpasien() {
        String[] judul = {"NO RM", "Kode RM", "Nama Pasien", "JK", "Alamat"};
        model = new DefaultTableModel(judul, 0);
        tblpasien.setModel(model);
        lebarKolom();
        String sql = "SELECT *, tbl_daerah.*, tbl_rm.* from tbl_rm"
                + " inner join tbl_daerah on tbl_daerah.kode_daerah = tbl_rm.kode_daerah"
                + " where nama_daerah='" + cbdaerah.getSelectedItem().toString() + "' "
                + " ORDER BY no_rm ASC";

        try {
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {
                String kodedaerah = rs.getString("kode_daerah");
                String norm = rs.getString("no_rm");
                String koderm = rs.getString("kode_rm");
                String nama = rs.getString("nama_pasien");
                String jk = rs.getString("jenis_kelamin");
                String alamat = rs.getString("alamat");

                tiddaerahrm.setText(kodedaerah);
                String[] data = {norm, koderm, nama, jk, alamat};
                model.addRow(data);

            }
        } catch (Exception e) {
            System.out.println(e);

        }

    }

    public void ID_AUTO() {
        try {
            String sql = "Select max(right(id_pendaftaran,5)) as no_idtransaksi from tbl_pelayanan";
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                System.out.println(rs.first());
                if (rs.first() == false) {
                    tidpendaftaran.setText("RJ-000001");

                } else {
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                    if (autoid <= 9) {
                        tidpendaftaran.setText("RJ-00000" + autoid);
                    } else if (autoid > 9 && autoid <= 99) {
                        tidpendaftaran.setText("RJ-0000" + autoid);
                    } else if (autoid > 99 && autoid <= 999) {
                        tidpendaftaran.setText("RJ-000" + autoid);
                    } else if (autoid > 999 && autoid <= 9999) {
                        tidpendaftaran.setText("RJ-00" + autoid);
                    } else if (autoid > 9999) {
                        tidpendaftaran.setText("RJ-0" + autoid);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error ID Pendaftaran" + e);
        }
    }

    public void NO_AUTO() {
        try {
            String sql = "Select max(right(no_pendaftaran,3)) from tbl_pendaftaran ";

            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    tnopendaftaran.setText("001");

                } else {
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                    String nomor = String.valueOf(autoid);

                    for (int a = 0; a < 2; a++) {
                        nomor = "0" + nomor;
                    }
                    tnopendaftaran.setText("" + nomor);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error NO Pendaftaran" + e);
        }
    }

    public void tanggal() {

        Calendar kal = new GregorianCalendar();
        int tahun = kal.get(Calendar.YEAR);
        int bulan = kal.get(Calendar.MONTH) + 1;
        int hari = kal.get(Calendar.DAY_OF_MONTH);

        if (bulan < 10) {
            String tanggal = tahun + "/0" + bulan + "/" + hari;
            ttanggal.setText(tanggal);
        } else {
            String tanggal = tahun + "/" + bulan + "/" + hari;

            ttanggal.setText(tanggal);
        }
    }

    public void Resetform() {
        tidpendaftaran.setText("~");
        tnopendaftaran.setText("Auto Fill");
        tnama.setText("");
        talamat.setText("");
        tnoidentitasrm.setText("");
        tnorm.setText("");
        tkodeanggota.setText("");
        tnamarm.setText("");
        talamatrm.setText("");
        tnoidentitasrm.setText("");
        talamatktprm.setText("");
        tnotelepomrm.setText("");
        tnomorrmpasien.setText("");
        tusia.setText("");

        tabelpasien();

        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
    }

    public void tampildaerah() {
        String sql = "SELECT * from tbl_daerah";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String daerah = rs.getString("nama_daerah");

                cbdaerahRM.addItem(daerah);
                cbdaerah.addItem(daerah);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void tampilpetugas() {
        String sql = "SELECT * from tbl_perawatan";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String poli = rs.getString("nama_petugas");

                cbpoli.addItem(poli);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void simpanpelayanan() {
        ID_AUTO();
        NO_AUTO();
        String ip = tidpendaftaran.getText();
        String np = tnopendaftaran.getText();
        String rm = tnomorrmpasien.getText();
        String usia = tusia.getText();
        String poli = cbpoli.getSelectedItem().toString();
        String kriteria = cbkriteria.getSelectedItem().toString();
        String jenisk = cbjeniskunjungan.getSelectedItem().toString();
        String petugas = cbpetugas.getSelectedItem().toString();
        String tanggal = ttanggal.getText();
        

        try {
            con.createStatement().executeUpdate("insert into tbl_pelayanan(id_pendaftaran,no_pendaftaran,kode_rm,umur,poli,kriteria_pengunjung,jenis_kunjungan,petugas_periksa,tanggal,user)"
                    + " values('" + ip + "','" + np + "','" + rm + "','" + usia + "','" + poli + "','" + kriteria + "','" + jenisk + "','" + petugas + "','" + tanggal + "','" + user + "')");
            con.createStatement().executeUpdate("insert into tbl_pendaftaran values('" + ip + "','" + np + "')");
            JOptionPane.showMessageDialog(null, "Berhasill !!");
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "gagal !!" + e);
        }
    }

    public void NORMAUTO() {
        String iddaerah = tiddaerahrm.getText();
        String sql = "select max(left(no_rm,5)) from tbl_rm where kode_daerah='" + iddaerah + "'";

        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    tnorm.setText("0001");

                } else {
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                    String nomor = String.valueOf(autoid);

                    for (int a = 0; a < 1; a++) {
                        nomor = "0" + nomor;
                    }
                    tnorm.setText("" + nomor);
                }

            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "NO RM Gagal dibuat !! " + e);
        }

    }

    public void lebarKolom() {
        TableColumn column;
        for (int i = 0; i < 4; i++) {
            column = tblpasien.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(10);
            } else if (i == 1) {
                column.setPreferredWidth(75);
            } else if (i == 2) {
                column.setPreferredWidth(150);
            } else if (i == 3) {
                column.setPreferredWidth(10);
            } else if (i == 4) {
                column.setPreferredWidth(180);
            }
        }
    }

    public void cetakperpasien() throws JRException {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

        
        String pasien = tnomorrmpasien.getText();
        JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/laporan/laporanpelayanan2.jrxml"));
        JRDesignQuery query = new JRDesignQuery();
        HashMap param = new HashMap();
        param.put("kriteria", pasien);
        query.setText("select *, tbl_rm.*"
                + " from tbl_pelayanan"
                + " inner join tbl_rm using(kode_rm)"
                + " where kode_rm='" + pasien + "'");
        jd.setQuery(query);
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
        JasperViewer.viewReport(jp, false);
    }
}


