/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.koneksiDB;
import config.Usersession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YOGI
 */
public class Daftarpasien_RI extends javax.swing.JFrame {

    /**
     * Creates new form DaftarTransaksi
     */
    String level = Usersession.getLevel();

    public Daftarpasien_RI() {
        initComponents();
        tampiltransaksi();

    }
    Connection con = koneksiDB.getConnection();
    ResultSet rs;
    DefaultTableModel model;
    DefaultTableModel modeljenis;
    PreparedStatement pst;

    //get user data session
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tidpendaftaran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btncetak = new javax.swing.JButton();
        namasiswa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tIDsiswa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, 50));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        tidpendaftaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tidpendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidpendaftaranActionPerformed(evt);
            }
        });
        tidpendaftaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tidpendaftaranKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID Pendaftaran   ");

        btncetak.setBackground(new java.awt.Color(102, 0, 255));
        btncetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncetak.setForeground(new java.awt.Color(255, 255, 255));
        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        namasiswa.setEditable(false);
        namasiswa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namasiswaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nama Pasien  ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Kode RM       ");

        tIDsiswa.setEditable(false);
        tIDsiswa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tIDsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIDsiswaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(180, 180, 180))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tIDsiswa)
                            .addComponent(tidpendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidpendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(tIDsiswa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 360, 420));

        tabeltransaksi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeltransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 760, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Daftar Seluruh Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 470, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CARI PASIEN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 180, 40));

        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        getContentPane().add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 560, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-CRUD_1.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tidpendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidpendaftaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidpendaftaranActionPerformed

    private void namasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namasiswaActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        try {
            cetaknota();
        } catch (Exception ex) {
            Logger.getLogger(Daftarpasien_RI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncetakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (level) {
            case "admin": {
                dashboard dsb = new dashboard();
                dsb.dashAdmin();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }

            default:
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tidpendaftaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidpendaftaranKeyReleased
        tampiltransaksi();
    }//GEN-LAST:event_tidpendaftaranKeyReleased

    private void tabeltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltransaksiMouseClicked
        int i = tabeltransaksi.getSelectedRow();
        tidpendaftaran.setText(model.getValueAt(i, 0).toString());
        namasiswa.setText(model.getValueAt(i, 3).toString());

        tIDsiswa.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_tabeltransaksiMouseClicked

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        tampiltransaksi();
    }//GEN-LAST:event_tCariKeyReleased

    private void tIDsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIDsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIDsiswaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int keputusan = JOptionPane.showConfirmDialog(null, "Data Yang dihapus tidak bisa kembali, Apakah Anda Yakin ??");

        switch (keputusan) {
            case JOptionPane.YES_OPTION:
            try {
                con.createStatement().executeUpdate("delete from tbl_rialkes where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ribiayapersalinan where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ricairan where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ridetalkes where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_riresep where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ridetcairan where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ridetpembayaran where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ridetpersalinan where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ridettablet where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ripelayanan where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ripembayaran where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ripenunjang where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_riperawatanbayi where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ripersalinan where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ritablet where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_ritindakanperawat where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("delete from tbl_rivisitedokter where id_pendaftaran='" + tidpendaftaran.getText() + "'");
               
                JOptionPane.showMessageDialog(null, "Berhasil !!!");

                resetform();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal !! " + e);
            }
            break;

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftarpasien_RI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftarpasien_RI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftarpasien_RI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftarpasien_RI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftarpasien_RI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namasiswa;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tIDsiswa;
    private javax.swing.JTable tabeltransaksi;
    private javax.swing.JTextField tidpendaftaran;
    // End of variables declaration//GEN-END:variables

    private void tampiltransaksi() {

        String[] judul = {"No Kwitansi", "Tanggal KRS", "Kode RM", "Nama Pasien", "Tagihan", "Petugas"};
        model = new DefaultTableModel(judul, 0);
        tabeltransaksi.setModel(model);

        String sql = "Select *,tbl_ripelayanan.*,tbl_rm.*, tbl_ripembayaran.* from tbl_ripelayanan"
                + " inner join tbl_rm on tbl_rm.kode_rm=tbl_ripelayanan.no_rm"
                + " inner join tbl_ripembayaran using(id_pendaftaran)"
                + " Where nama_pasien like'%" + tCari.getText() + "%' OR kode_rm like'%" + tCari.getText() + "%' ";

        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String id = rs.getString("id_pendaftaran");
                String tgl = rs.getString("tanggal_krs");
                String kodesiswa = rs.getString("kode_rm");
                String nama = rs.getString("nama_pasien");
                String jml = rs.getString("total_tagihan");
                String user = rs.getString("user");

                String[] data = {id, tgl, kodesiswa, nama, jml, user};
                model.addRow(data);

            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void cetaknota() throws Exception {

        try {
            String total = tidpendaftaran.getText();
            String tgl = model.getValueAt(tabeltransaksi.getSelectedRow(), 1).toString();
            JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/laporan/notarawatinap.jrxml"));
            JRDesignQuery query = new JRDesignQuery();
            HashMap param = new HashMap();
            param.put("tanggal", tgl);
            query.setText("select tbl_ripelayanan.*,tbl_rm.nama_pasien,"
                    + " tbl_ripembayaran.total_tagihan,tbl_ripembayaran.user, tbl_ridetpembayaran.*,tbl_obat.nama_obat,tbl_obat.harga_jual,"
                    + " tbl_riresep.* from tbl_ripelayanan "
                    + " inner join tbl_rm on tbl_rm.kode_rm=tbl_ripelayanan.no_rm "
                    + " inner join tbl_ripembayaran using(id_pendaftaran)"
                    + " inner join tbl_ridetpembayaran USING(id_pendaftaran)"
                    + " inner join tbl_riresep USING(id_pendaftaran)"
                    + " inner join tbl_obat on tbl_obat.id_obat=tbl_riresep.id_obat "
                    + " where id_pendaftaran='" + tidpendaftaran.getText() + "' order by ket ASC");
            jd.setQuery(query);

            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void resetform() {
        tidpendaftaran.setText("");
        namasiswa.setText("");
        tIDsiswa.setText("");
        tampiltransaksi();
    }
}
