/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Usersession;
import config.koneksiDB;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YOGI
 */
public class daftar_pasienRI extends javax.swing.JFrame {

    /**
     * Creates new form daftar_pasienRI
     */
    String level = Usersession.getLevel();

    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

    public daftar_pasienRI() {
        initComponents();
        tampilkamar();
        tabelpasien();
        tanggal();

        btnsimpan.setEnabled(false);

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
    }
    Statement st;
    Connection con = koneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;
    DefaultTableModel modelkamar;
    DefaultTableModel modeltagihan;
    DefaultTableModel modelicd;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihkamar = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblkamar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tcarikamar = new javax.swing.JTextField();
        tabelicd = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblicd = new javax.swing.JTable();
        tcari1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        tcari = new javax.swing.JTextField();
        btnkembali = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnresep = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tkoderm = new javax.swing.JTextField();
        tnamapasien = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        truangkamar = new javax.swing.JTextField();
        tusia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticd = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        tketerangan = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tidpendaftaran = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ttanggal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btncairan = new javax.swing.JButton();
        btninjeksi = new javax.swing.JButton();
        btntablet = new javax.swing.JButton();
        tperawatanbayi = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tregister = new javax.swing.JLabel();
        tdaftarpasien = new javax.swing.JLabel();
        tlaboratorium = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        tpersalinan = new javax.swing.JLabel();
        ttindakanperawat = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jeniskunjunganbl = new javax.swing.JLabel();

        pilihkamar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pilihkamar.setLocation(new java.awt.Point(300, 100));
        pilihkamar.setMinimumSize(new java.awt.Dimension(800, 500));
        pilihkamar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Form Pilih Kamar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(301, 301, 301))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        pilihkamar.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 780, 60));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        tblkamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblkamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblkamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkamarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblkamar);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cari Kamar");

        tcarikamar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tcarikamar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tcarikamar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pilihkamar.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 780, 390));

        tabelicd.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tabelicd.setMinimumSize(new java.awt.Dimension(720, 491));
        tabelicd.setUndecorated(true);
        tabelicd.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("CARI KODE ICD");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        tabelicd.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 715, -1));

        jPanel6.setBackground(new java.awt.Color(0, 255, 204));

        tblicd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblicd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblicdKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblicd);

        tcari1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tcari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcari1KeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("CARI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(65, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tcari1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tcari1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        tabelicd.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 430));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblpasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 560, 510));

        tcari.setBackground(new java.awt.Color(102, 255, 255));
        tcari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 430, 40));

        btnkembali.setBackground(new java.awt.Color(51, 51, 255));
        btnkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("DASHBOARD");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Cari Pasien");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 110, 40));

        btnresep.setBackground(new java.awt.Color(0, 153, 204));
        btnresep.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btnresep.setText("+ Visite Dokter");
        btnresep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresepActionPerformed(evt);
            }
        });
        getContentPane().add(btnresep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 90, 140, 40));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kode RM");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nama Pasien");

        tkoderm.setEditable(false);
        tkoderm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tnamapasien.setEditable(false);
        tnamapasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnsimpan.setBackground(new java.awt.Color(51, 51, 255));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(153, 204, 0));
        btnbatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Diagnosa");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Ruang Kamar");

        truangkamar.setEditable(false);
        truangkamar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tusia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Usia");

        ticd.setColumns(20);
        ticd.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        ticd.setRows(5);
        jScrollPane2.setViewportView(ticd);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Keterangan");

        tketerangan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnhapus.setBackground(new java.awt.Color(255, 102, 51));
        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        jButton1.setText("Pindah Kamar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("* Terapi pulang/lainnya");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("ID Pendaftaran");

        tidpendaftaran.setEditable(false);
        tidpendaftaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton4.setBackground(new java.awt.Color(153, 255, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Cari ICD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tusia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(truangkamar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tketerangan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel1)))
                            .addComponent(tnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(tkoderm, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(24, 24, 24)
                        .addComponent(tidpendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidpendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tkoderm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(truangkamar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tusia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tketerangan, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 550, 510));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tanggal :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 80, 20));

        ttanggal.setEditable(false);
        ttanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ttanggal.setText("yyy/mm/dd");
        getContentPane().add(ttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, 130, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Daftar Pasien Rawat Inap");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 520, 40));

        btncairan.setBackground(new java.awt.Color(0, 153, 255));
        btncairan.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btncairan.setText("+ Injeksi&Cairan");
        btncairan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncairanActionPerformed(evt);
            }
        });
        getContentPane().add(btncairan, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, -1, 40));

        btninjeksi.setBackground(new java.awt.Color(0, 153, 204));
        btninjeksi.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btninjeksi.setText("+ Alkes");
        btninjeksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninjeksiActionPerformed(evt);
            }
        });
        getContentPane().add(btninjeksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 120, 40));

        btntablet.setBackground(new java.awt.Color(255, 255, 153));
        btntablet.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        btntablet.setText("+ Oral");
        btntablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntabletActionPerformed(evt);
            }
        });
        getContentPane().add(btntablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 90, 110, 40));

        tperawatanbayi.setFont(new java.awt.Font("Tekton Pro", 1, 15)); // NOI18N
        tperawatanbayi.setForeground(new java.awt.Color(255, 255, 255));
        tperawatanbayi.setText("Perawatan Bayi");
        tperawatanbayi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tperawatanbayiMouseClicked(evt);
            }
        });
        getContentPane().add(tperawatanbayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 20));

        jLabel25.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Form tagihan");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 130, 20));

        tregister.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        tregister.setForeground(new java.awt.Color(255, 255, 255));
        tregister.setText("Register");
        tregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tregisterMouseClicked(evt);
            }
        });
        getContentPane().add(tregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 20));

        tdaftarpasien.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        tdaftarpasien.setForeground(new java.awt.Color(255, 255, 255));
        tdaftarpasien.setText("Daftar Pasien");
        tdaftarpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdaftarpasienMouseClicked(evt);
            }
        });
        getContentPane().add(tdaftarpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 20));

        tlaboratorium.setFont(new java.awt.Font("Tekton Pro", 1, 15)); // NOI18N
        tlaboratorium.setForeground(new java.awt.Color(255, 255, 255));
        tlaboratorium.setText("Penunjang");
        tlaboratorium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlaboratoriumMouseClicked(evt);
            }
        });
        getContentPane().add(tlaboratorium, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jPanel4.setBackground(new java.awt.Color(51, 255, 204));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("@ Copyright 2020");
        jLabel26.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(503, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(487, 487, 487))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 1150, 50));

        tpersalinan.setFont(new java.awt.Font("Tekton Pro", 1, 15)); // NOI18N
        tpersalinan.setForeground(new java.awt.Color(255, 255, 255));
        tpersalinan.setText("Persalinan");
        tpersalinan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpersalinanMouseClicked(evt);
            }
        });
        getContentPane().add(tpersalinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 20));

        ttindakanperawat.setFont(new java.awt.Font("Tekton Pro", 1, 15)); // NOI18N
        ttindakanperawat.setForeground(new java.awt.Color(255, 255, 255));
        ttindakanperawat.setText("Tindakan Perawat");
        ttindakanperawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttindakanperawatMouseClicked(evt);
            }
        });
        getContentPane().add(ttindakanperawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 200, 130, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/formmenu.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jeniskunjunganbl.setText("jLabel6");
        getContentPane().add(jeniskunjunganbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpasienMouseClicked
        int i = tblpasien.getSelectedRow();
        tidpendaftaran.setText(model.getValueAt(i, 0).toString());
        tkoderm.setText(model.getValueAt(i, 1).toString());
        tnamapasien.setText(model.getValueAt(i, 2).toString());
        truangkamar.setText(model.getValueAt(i, 3).toString());

        String sql = "select * from tbl_ripelayanan where id_pendaftaran='" + tidpendaftaran.getText() + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String usia = rs.getString("usia");
                String ket = rs.getString("catatan");
                String diagnosa = rs.getString("diagnosa");
                String Jkunjungan = rs.getString("jenis_kunjungan");
                jeniskunjunganbl.setText(Jkunjungan);
                tusia.setText(usia);
                tketerangan.setText(ket);
                ticd.setText(diagnosa);

            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Gagal mengambil data !! " + e);
        }

        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);


    }//GEN-LAST:event_tblpasienMouseClicked

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed

    }//GEN-LAST:event_tcariActionPerformed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        tabelpasien();
    }//GEN-LAST:event_tcariKeyReleased

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        switch (level) {
            case "admin": {

                dashboard dsb = new dashboard();
                dsb.dashAdmin();
//                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "receptionist": {

                dashboard dsb = new dashboard();
                dsb.dashReceptionist();
//                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "dokter": {

                dashboard dsb = new dashboard();
                dsb.dashDokter();
//                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "apoteker": {

                dashboard dsb = new dashboard();
                dsb.dashApoteker();
//                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            default:
                break;
        }
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnresepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresepActionPerformed

        String idpendaftaran = tidpendaftaran.getText();
        if (idpendaftaran.length() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih ID pendaftaran terlebih dahulu !!");

        } else {
            CRUD_lain lb = new CRUD_lain();
            lb.tidpendaftaran.setText(tidpendaftaran.getText());
            lb.tnamapasien.setText(tnamapasien.getText());
            lb.tabelivisitedokter();
            lb.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnresepActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        int i = tblpasien.getSelectedRow();
        String ruang = model.getValueAt(i, 3).toString();
        String rkamar = truangkamar.getText();
        String usia = tusia.getText();
        String ket = tketerangan.getText();
        String diagnosa = ticd.getText();
        if (rkamar.equals(ruang)) {
            try {
                con.createStatement().executeUpdate("update tbl_ripelayanan set nama_kamar='" + rkamar + "',usia='" + usia + "',catatan='" + ket + "',diagnosa='" + diagnosa + "'"
                        + " where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                simpanICD();
                simpandatasakit();
                JOptionPane.showMessageDialog(null, "Berhasill !!");
                resetform();
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Gagal !!" + e);
            }
        } else {
            try {
                con.createStatement().executeUpdate("update tbl_ripelayanan set nama_kamar='" + rkamar + "',usia='" + usia + "',catatan='" + ket + "',diagnosa='" + diagnosa + "'"
                        + " where id_pendaftaran='" + tidpendaftaran.getText() + "'");
                con.createStatement().executeUpdate("update tbl_rikamar set status_kamar='kosong' where nama_kamar='" + rkamar + "'");
                con.createStatement().executeUpdate("update tbl_rikamar set status_kamar='kosong' where nama_kamar='" + ruang + "'");
                simpanICD();
                simpandatasakit();
                JOptionPane.showMessageDialog(null, "Berhasill dong !!");
                resetform();
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Gagal !!" + e);
            }
        }

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        resetform();

    }//GEN-LAST:event_btnbatalActionPerformed

    private void btninjeksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninjeksiActionPerformed

        String idpendaftaran = tidpendaftaran.getText();
        if (idpendaftaran.length() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih ID pendaftaran terlebih dahulu !!");

        } else {
            CRUD_alkes lb = new CRUD_alkes();
            lb.tidpendaftaran.setText(tidpendaftaran.getText());
            lb.tnamapasien.setText(tnamapasien.getText());
            lb.tabelinjeksi();
            lb.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btninjeksiActionPerformed

    private void btncairanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncairanActionPerformed
        String idpendaftaran = tidpendaftaran.getText();
        if (idpendaftaran.length() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih ID pendaftaran terlebih dahulu !!");

        } else {

            CRUD_cairan lb = new CRUD_cairan();
            lb.tidpendaftaran.setText(tidpendaftaran.getText());
            lb.tnamapasien.setText(tnamapasien.getText());
            lb.tabelinjeksi();
            lb.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btncairanActionPerformed

    private void btntabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntabletActionPerformed
        String idpendaftaran = tidpendaftaran.getText();
        if (idpendaftaran.length() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih ID pendaftaran terlebih dahulu !!");

        } else {

            CRUD_tablet lb = new CRUD_tablet();
            lb.tidpendaftaran.setText(tidpendaftaran.getText());
            lb.tnamapasien.setText(tnamapasien.getText());
            lb.tabelinjeksi();
            lb.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btntabletActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            con.createStatement().executeUpdate("delete from tbl_ripelayanan where id_pendaftaran='" + tidpendaftaran.getText() + "'");
            con.createStatement().executeUpdate("update tbl_rikamar set status_kamar='kosong' where nama_kamar='" + truangkamar.getText() + "'");
            JOptionPane.showMessageDialog(null, "Berhasill !! ");
            resetform();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Gagal !! " + e);

        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tregisterMouseClicked
        new register_rawatinap().setVisible(true);
        dispose();

    }//GEN-LAST:event_tregisterMouseClicked

    private void tdaftarpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdaftarpasienMouseClicked
        new daftar_pasienRI().setVisible(true);
        dispose();

    }//GEN-LAST:event_tdaftarpasienMouseClicked

    private void tblkamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkamarMouseClicked
        int i = tblkamar.getSelectedRow();
        int keputusan = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ??");

        switch (keputusan) {
            case JOptionPane.YES_OPTION:
                truangkamar.setText(modelkamar.getValueAt(i, 1).toString());
                pilihkamar.dispose();

                break;
        }
    }//GEN-LAST:event_tblkamarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pilihkamar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        formtagihan_RI lb = new formtagihan_RI();
        lb.tidpendaftaran.setText(tidpendaftaran.getText());
        lb.tnamapasien.setText(tnamapasien.getText());
        lb.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel25MouseClicked

    private void tperawatanbayiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tperawatanbayiMouseClicked
        String idpendaftaran = tidpendaftaran.getText();
        if (idpendaftaran.length() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih ID pendaftaran terlebih dahulu !!");

        } else {

            perawatan_bayi lb = new perawatan_bayi();
            lb.tidpendaftaran.setText(tidpendaftaran.getText());
            lb.tnamapasien.setText(tnamapasien.getText());
            lb.tampiltindakanpemeriksaan();
            lb.setVisible(true);
            dispose();

        }

    }//GEN-LAST:event_tperawatanbayiMouseClicked

    private void tlaboratoriumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlaboratoriumMouseClicked
        String idpendaftaran = tidpendaftaran.getText();
        if (idpendaftaran.length() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih ID pendaftaran terlebih dahulu !!");

        } else {

            tambah_penunjangRI lb = new tambah_penunjangRI();
            lb.tidpendaftaran.setText(tidpendaftaran.getText());
            lb.tnamapasien.setText(tnamapasien.getText());
            lb.tampilobatpemeriksaan();
            lb.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_tlaboratoriumMouseClicked

    private void ttindakanperawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttindakanperawatMouseClicked
        String idpendaftaran = tidpendaftaran.getText();
        if (idpendaftaran.length() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih ID pendaftaran terlebih dahulu !!");

        } else {

            tambah_tindakanRI lb = new tambah_tindakanRI();
            lb.tidpendaftaran.setText(tidpendaftaran.getText());
            lb.tnamapasien.setText(tnamapasien.getText());
            lb.tampiltindakanpemeriksaan();
            lb.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_ttindakanperawatMouseClicked

    private void tpersalinanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpersalinanMouseClicked
        String idpendaftaran = tidpendaftaran.getText();
        if (idpendaftaran.length() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih ID pendaftaran terlebih dahulu !!");

        } else {

            CRUD_persalinan lb = new CRUD_persalinan();
            lb.tidpendaftaran.setText(tidpendaftaran.getText());
            lb.tnamapasien.setText(tnamapasien.getText());
            lb.tabelinjeksi();
            lb.tampiljenispersalinan();
            lb.cekjenispersalinan();

            lb.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_tpersalinanMouseClicked

    private void tblicdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblicdKeyPressed
        int i = tblicd.getSelectedRow();
        ticd.setText(modelicd.getValueAt(i, 0).toString());
        tabelicd.dispose();
    }//GEN-LAST:event_tblicdKeyPressed

    private void tcari1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcari1KeyReleased
        tampilICD();        // TODO add your handling code here:
    }//GEN-LAST:event_tcari1KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tabelicd.setVisible(true);
        tampilICD();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar_pasienRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar_pasienRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar_pasienRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar_pasienRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar_pasienRI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncairan;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btninjeksi;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnresep;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntablet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jeniskunjunganbl;
    private javax.swing.JFrame pilihkamar;
    private javax.swing.JFrame tabelicd;
    private javax.swing.JTable tblicd;
    private javax.swing.JTable tblkamar;
    private javax.swing.JTable tblpasien;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tcari1;
    private javax.swing.JTextField tcarikamar;
    private javax.swing.JLabel tdaftarpasien;
    private javax.swing.JTextArea ticd;
    private javax.swing.JTextField tidpendaftaran;
    private javax.swing.JTextField tketerangan;
    private javax.swing.JTextField tkoderm;
    private javax.swing.JLabel tlaboratorium;
    private javax.swing.JTextField tnamapasien;
    private javax.swing.JLabel tperawatanbayi;
    private javax.swing.JLabel tpersalinan;
    private javax.swing.JLabel tregister;
    private javax.swing.JTextField truangkamar;
    private javax.swing.JTextField ttanggal;
    private javax.swing.JLabel ttindakanperawat;
    private javax.swing.JTextField tusia;
    // End of variables declaration//GEN-END:variables
public void tabelpasien() {
        String[] judul = {"ID Pendaftaran", "NO RM", "Nama Pasien", "Ruang Kamar", "JK"};
        model = new DefaultTableModel(judul, 0);
        tblpasien.setModel(model);
        String sql = "SELECT *, tbl_rm.*, tbl_ripelayanan.* from tbl_ripelayanan"
                + " inner join tbl_rm on tbl_rm.kode_rm=tbl_ripelayanan.no_rm "
                + " where status_pasien='dirawat' and nama_pasien like'%" + tcari.getText() + "%' ORDER BY id_pendaftaran DESC";

        try {
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {
                String idpendaftaran = rs.getString("id_pendaftaran");
                String norm = rs.getString("no_rm");
                String nama = rs.getString("nama_pasien");
                String rkamar = rs.getString("nama_kamar");
                String jk = rs.getString("jenis_kelamin");

                String[] data = {idpendaftaran, norm, nama, rkamar, jk};
                model.addRow(data);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void resetform() {
        tidpendaftaran.setText("");
        tkoderm.setText("");
        tnamapasien.setText("");
        truangkamar.setText("");
        tusia.setText("");
        tketerangan.setText("");
        ticd.setText("");

        btnsimpan.setEnabled(false);
        btnresep.setEnabled(false);
        tampilkamar();
        tabelpasien();
    }

    public void tanggal() {

        Calendar kal = new GregorianCalendar();
        int tahun = kal.get(Calendar.YEAR);
        int bulan = kal.get(Calendar.MONTH) + 1;
        int hari = kal.get(Calendar.DAY_OF_MONTH);

        if (bulan < 10) {
            String tanggal = tahun + "-0" + bulan + "-" + hari;
            ttanggal.setText(tanggal);
        } else {
            String tanggal = tahun + "-" + bulan + "-" + hari;

            ttanggal.setText(tanggal);
        }
    }

    public void tampilkamar() {
        String[] judul = {"ID Kamar", "Nama Kamar", "Level Kamar", "Harga Per hari", "Status Kamar"};
        modelkamar = new DefaultTableModel(judul, 0);
        tblkamar.setModel(modelkamar);
        String sql = "select * from tbl_rikamar where status_kamar='kosong' and nama_kamar like '%" + tcarikamar.getText() + "%' ";

        try {
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {

                String id = rs.getString("id_kamar");
                String nama = rs.getString("nama_kamar");
                String level = rs.getString("level_kamar");
                String harga = rs.getString("harga_kamar");
                String status = rs.getString("status_kamar");

                String[] data = {id, nama, level, harga, status};
                modelkamar.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);

        }

    }

    public void tampilICD() {
        String[] judul = {"Kode ICD", "Nama Penyakit"};
        modelicd = new DefaultTableModel(judul, 0);
        tblicd.setModel(modelicd);
        String sql = "SELECT * from tbl_icd where nama_icd like'%" + tcari.getText() + "%'";

        try {
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {

                String kode = rs.getString("kode_icd");
                String nama = rs.getString("nama_icd");

                String[] data = {kode, nama};
                modelicd.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);

        }

    }

    public void simpanICD() {
        String sql = "Select datediff(now(),tanggal_lahir) as umur from tbl_rm where kode_rm='" + tkoderm.getText() + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                int umur = Integer.parseInt(rs.getString("umur"));
                String JKunjungan = jeniskunjunganbl.getText();
                String jk = model.getValueAt(tblpasien.getSelectedRow(), 4).toString();

                if (umur <= 7) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 7hbl=7hbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 7hbp=7hbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 7hll=7hll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 7hlp=7hlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 8 && umur <= 28) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 28hbl=28hbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 28hbp=28hbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 28hll=28hll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 28hlp=28hlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 29 && umur <= 365) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 1tbl=1tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 1tbp=1tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 1tll=1tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 1tlp=1tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 366 && umur <= 1460) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 4tbl=4tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 4tbp=4tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 4tll=4tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 4tlp=4tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 1461 && umur <= 3285) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 9tbl=9tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 9tbp=9tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 9tll=9tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 9tlp=9tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 3286 && umur <= 5110) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 14tbl=14tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 14tbp=14tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 14tll=14tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 14tlp=14tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 5111 && umur <= 6935) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 19tbl=19tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 19tbp=19tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 19tll=19tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 19tlp=19tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 6936 && umur <= 16060) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 44tbl=44tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 44tbp=44tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 44tll=44tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 44tlp=44tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 16061 && umur <= 19710) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 54tbl=54tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 54tbp=54tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 54tll=54tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 54tlp=54tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 19711 && umur <= 21535) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 59tbl=59tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 59tbp=59tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 59tll=59tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 59tlp=59tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 21536 && umur <= 23360) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 64tbl=64tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 64tbp=64tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 64tll=64tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 64tlp=64tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 23361 && umur <= 25185) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 69tbl=69tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 69tbp=69tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 69tll=69tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 69tlp=69tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                } else if (umur >= 25186) {

                    switch (JKunjungan) {

                        case "Baru":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 70tbl=70tbl+1,jbl=jbl+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 70tbp=70tbp+1,jbp=jbp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            }
                            break;
                        case "Lama":
                            if (jk.equals("L")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 70tll=70tll+1,jll=jll+1,total_laki=total_laki+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");
                            } else if (jk.equals("P")) {
                                con.createStatement().executeUpdate("update tbl_ICD set 70tlp=70tlp+1,jlp=jlp+1,total_perempuan=total_perempuan+1,jumlah_total=jumlah_total+1 where kode_icd='" + ticd.getText() + "'");

                            }
                            break;
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal menyimpan Laporan ICD !! " + e);
        }
    }

    public void simpandatasakit() {
        String rm = tkoderm.getText();
        String umur = tusia.getText();
        String tanggal = ttanggal.getText();
        
        String icd = ticd.getText();
        try {
            con.createStatement().executeUpdate("insert into tbl_datasakit(kode_rm,umur,tanggal_periksa,kode_icd) values("
                    + "'" + rm + "','" + umur + "','" + tanggal + "','" + icd + "')");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Insert ke tbl_datasakit " + e);
        }
    }
}
