/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Usersession;
import config.koneksiDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YOGI
 */
public class data_sakit extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_user
     */
    String level = Usersession.getLevel();

    public data_sakit() {
        initComponents();
        tabelAdmin();
        tiduser.setEnabled(false);

        tiduser.setText("Auto Fill");
        btnhapus.setEnabled(false);
    }
    Statement st;
    Connection con = koneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnrefresh = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbladmin = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tiduser = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tpltpulang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        telp = new javax.swing.JTextField();
        tpltdatang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbbulan = new javax.swing.JComboBox<>();
        btnrefresh1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tawal = new javax.swing.JLabel();
        takhir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnrefresh.setBackground(new java.awt.Color(51, 51, 255));
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("CETAK LAPORAN");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, 160, 48));

        btnkembali.setBackground(new java.awt.Color(51, 51, 255));
        btnkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("DASHBOARD");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KELOLA DATA DB");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 460, 40));

        tCari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        getContentPane().add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 470, 40));

        tbladmin.setBackground(new java.awt.Color(0, 204, 204));
        tbladmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbladmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbladminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbladmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 670, 320));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kode RM");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PLT Pulang");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NAMA LENGKAP");

        tiduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiduserActionPerformed(evt);
            }
        });

        tNama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });

        tpltpulang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tpltpulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpltpulangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Keterangan");

        btnsimpan.setBackground(new java.awt.Color(51, 51, 255));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(153, 153, 0));
        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        telp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tpltdatang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tpltdatang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpltdatangActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("PLT datang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpltdatang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tiduser)
                            .addComponent(tNama, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telp)
                            .addComponent(tpltpulang))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiduser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpltdatang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpltpulang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 360, 420));

        cbbulan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbbulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbulanActionPerformed(evt);
            }
        });
        getContentPane().add(cbbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 140, 40));

        btnrefresh1.setBackground(new java.awt.Color(51, 51, 255));
        btnrefresh1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh1.setText("Refresh form");
        btnrefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefresh1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 160, 48));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-CRUD_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tawal.setText("jLabel7");
        getContentPane().add(tawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        takhir.setText("jLabel7");
        getContentPane().add(takhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        switch (level) {
            case "admin": {

                dashboard dsb = new dashboard();
                dsb.dashAdmin();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "receptionist": {

                dashboard dsb = new dashboard();
                dsb.dashReceptionist();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "dokter": {

                dashboard dsb = new dashboard();
                dsb.dashDokter();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "apoteker": {

                dashboard dsb = new dashboard();
                dsb.dashApoteker();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            default:
                break;
        }
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        tabelAdmin();
    }//GEN-LAST:event_tCariActionPerformed

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        tabelAdmin();
    }//GEN-LAST:event_tCariKeyReleased

    private void tbladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbladminMouseClicked
        int i = tbladmin.getSelectedRow();
        tiduser.setText(model.getValueAt(i, 0).toString());
        tNama.setText(model.getValueAt(i, 1).toString());
        tpltdatang.setText(model.getValueAt(i, 3).toString());
        tpltpulang.setText(model.getValueAt(i, 4).toString());
        telp.setText(model.getValueAt(i, 5).toString());

        //  disabled item on klik row table
        tiduser.setEnabled(false);
        btnhapus.setEnabled(true);
    }//GEN-LAST:event_tbladminMouseClicked

    private void tiduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiduserActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void tpltpulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpltpulangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpltpulangActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

        String id = tiduser.getText();
        String pltpulang = tpltpulang.getText();
        String pltdatang = tpltdatang.getText();
        String nama = tNama.getText();
        String ket = telp.getText();
        String tanggal = model.getValueAt(tbladmin.getSelectedRow(), 2).toString();
        System.out.println(tanggal);

        if (nama.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukan data dengan benar!!");
            Resetform();

        } else {

            try {
                con.createStatement().executeUpdate("update tbl_datasakit set plt_datang='" + pltdatang + "',"
                        + "plt_pulang='" + pltpulang + "',keterangan='" + ket + "' where kode_rm='" + id + "' and"
                        + " tanggal_periksa='" + tanggal + "'");

                JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
                Resetform();
            } catch (Exception ex) {
                System.out.println("" + ex);
                JOptionPane.showMessageDialog(null, "Gagal !! Isi Form Dengan Benar ");
            }

        }


    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int keputusan = JOptionPane.showConfirmDialog(this, "apakah anda yakinmenghapus data ini? ");
        switch (keputusan) {
            case JOptionPane.YES_OPTION:
                try {
                    con.createStatement().executeUpdate("delete from tbl_datasakit where kode_rm = '" + model.getValueAt(tbladmin.getSelectedRow(), 0) + "'"
                            + " and tanggal_periksa='" + model.getValueAt(tbladmin.getSelectedRow(), 2) + "'");
                    JOptionPane.showMessageDialog(null, "Berhasil");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal !!!");

                }
                Resetform();
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tpltdatangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpltdatangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpltdatangActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        try {
            cetaklaporan();
        } catch (JRException ex) {
            Logger.getLogger(data_sakit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnrefreshActionPerformed

    private void cbbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbulanActionPerformed
        Calendar kal = new GregorianCalendar();
        int tahun = kal.get(Calendar.YEAR);
        String bulan = cbbulan.getSelectedItem().toString();
        if (bulan == "Januari") {
            tawal.setText(tahun + "-01-01");
            takhir.setText(tahun + "-01-31");
            tabelAdmin();

        } else if (bulan == "Febuari") {
            tawal.setText(tahun + "-02-01");
            takhir.setText(tahun + "-02-29");
            tabelAdmin();
        } else if (bulan == "Maret") {
            tawal.setText(tahun + "-03-01");
            takhir.setText(tahun + "-03-31");
            tabelAdmin();
        } else if (bulan == "April") {
            tawal.setText(tahun + "-04-01");
            takhir.setText(tahun + "-04-30");
            tabelAdmin();
        } else if (bulan == "Mei") {
            tawal.setText(tahun + "-05-01");
            takhir.setText(tahun + "-05-31");
            tabelAdmin();
        } else if (bulan == "Juni") {
            tawal.setText(tahun + "-06-01");
            takhir.setText(tahun + "-06-30");
            tabelAdmin();
        } else if (bulan == "Juli") {
            tawal.setText(tahun + "-07-01");
            takhir.setText(tahun + "-07-31");
            tabelAdmin();
        } else if (bulan == "Agustus") {
            tawal.setText(tahun + "-08-01");
            takhir.setText(tahun + "-08-31");
            tabelAdmin();
        } else if (bulan == "September") {
            tawal.setText(tahun + "-09-01");
            takhir.setText(tahun + "-09-30");
            tabelAdmin();
        } else if (bulan == "Oktober") {
            tawal.setText(tahun + "-10-01");
            takhir.setText(tahun + "-10-31");
            tabelAdmin();
        } else if (bulan == "November") {
            tawal.setText(tahun + "-11-01");
            takhir.setText(tahun + "-11-30");
            tabelAdmin();
        } else if (bulan == "Desember") {
            tawal.setText(tahun + "-12-01");
            takhir.setText(tahun + "-12-31");
            tabelAdmin();
        }

    }//GEN-LAST:event_cbbulanActionPerformed

    private void btnrefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefresh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrefresh1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_sakit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_sakit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_sakit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_sakit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_sakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnrefresh1;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cbbulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tNama;
    private javax.swing.JLabel takhir;
    private javax.swing.JLabel tawal;
    private javax.swing.JTable tbladmin;
    private javax.swing.JTextField telp;
    private javax.swing.JTextField tiduser;
    private javax.swing.JTextField tpltdatang;
    private javax.swing.JTextField tpltpulang;
    // End of variables declaration//GEN-END:variables
 private void tabelAdmin() {
        String[] judul = {"Kode RM", "Nama Pasien", "Tanggal", "PLT datang", "PLT Pulang", "Keterangan"};
        model = new DefaultTableModel(judul, 0);
        tbladmin.setModel(model);
        String sql = "SELECT *, tbl_rm.nama_pasien FROM tbl_datasakit"
                + " inner join tbl_rm using(kode_rm) where kode_icd ='A90' and (tanggal_periksa BETWEEN '" + tawal.getText() + "' AND '" + takhir.getText() + "')";

        try {
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {
                String id = rs.getString("kode_rm");
                String nama = rs.getString("nama_pasien");
                String user = rs.getString("tanggal_periksa");
                String pass = rs.getString("plt_datang");
                String Telp = rs.getString("plt_pulang");
                String level = rs.getString("keterangan");

                String[] data = {id, nama, user, pass, Telp, level};
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);

        }
    }

    public void ID_AUTO() {
        try {
            String sql = "Select max(right(id_user,2)) as no_iduser from tbl_user";
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    tiduser.setText("U-01");

                } else {
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                    String nomor = String.valueOf(autoid);

                    for (int a = 0; a < 1; a++) {
                        nomor = "0" + nomor;
                    }
                    tiduser.setText("U-" + nomor);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "masukan data dengan benar!!");
        }
    }

    private void Resetform() {

        tNama.setText("");
        tpltpulang.setText("");
        telp.setText("");
        tpltdatang.setText("");

        tabelAdmin();

        btnsimpan.setEnabled(true);

        tiduser.setEnabled(true);
        tiduser.setEnabled(false);
        tiduser.setText("Auto Fill");
        btnhapus.setEnabled(false);

    }

    public void cetaklaporan() throws JRException {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

        String bulan = cbbulan.getSelectedItem().toString();
        int jmlpasien = tbladmin.getRowCount();
        String jumlahpasien = String.valueOf(jmlpasien);
        JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/laporan/laporan_db.jrxml"));
        JRDesignQuery query = new JRDesignQuery();
        HashMap param = new HashMap();
        param.put("bulan", bulan);
        param.put("jumlahpasien", jumlahpasien);
        query.setText("SELECT *, tbl_rm.* FROM tbl_datasakit"
                + " inner join tbl_rm using(kode_rm) where kode_icd ='A90' "
                + " and (tanggal_periksa BETWEEN '" + tawal.getText() + "' AND '" + takhir.getText() + "')");
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
        JasperViewer.viewReport(jp, false);

    }

}
