/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Usersession;
import config.koneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YOGI
 */
public class formtagihan_RI extends javax.swing.JFrame {

    /**
     * Creates new form formtagihan_RI
     */
    String user = Usersession.getNama();

    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

    public formtagihan_RI() {
        initComponents();
        tanggal();
        btnsimpantagihan.setEnabled(false);
        tbayar.setEnabled(false);
        btnsimpancetak.setEnabled(false);
        //set mata uang
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
    }
    Statement st;
    Connection con = koneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;
    DefaultTableModel modelpasien;
    
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formpasien = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tcari = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnhitung = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbiayakamar = new javax.swing.JTextField();
        tvisitedokter = new javax.swing.JTextField();
        tjumlahhari = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tbiayaalkes = new javax.swing.JTextField();
        tbiayacairan = new javax.swing.JTextField();
        tbiayatablet = new javax.swing.JTextField();
        ttanggal = new javax.swing.JTextField();
        tjumlahvisite = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ttindakanperawat = new javax.swing.JTextField();
        tpersalinan = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tperawatanbayi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tnamapasien = new javax.swing.JTextField();
        tidpendaftaran = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btncaripasien = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ttotaltagihan = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tbayar = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tkembalian = new javax.swing.JTextField();
        btnsimpancetak = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btncetaksaja = new javax.swing.JButton();
        tbiayaambulan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tbiayapenunjang = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tbiayaadmin = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnsimpantagihan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        tidkamar = new javax.swing.JLabel();
        ttotaltagihanbl = new javax.swing.JLabel();

        formpasien.setMinimumSize(new java.awt.Dimension(771, 512));
        formpasien.setUndecorated(true);
        formpasien.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Form Cari Pasien");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(313, 313, 313))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        formpasien.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));

        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(" Cari Pasien");

        tblpasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblpasienKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblpasien);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pilih");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        formpasien.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 761, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tanggal KRS");

        btnhitung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Biaya Kamar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Visite Dokter");

        tbiayakamar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tvisitedokter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tjumlahhari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tjumlahhari.setText("X");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Hari");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Biaya Alkes");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Biaya Injeksi&Cairan");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Biaya Oral");

        tbiayaalkes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbiayaalkes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbiayaalkesActionPerformed(evt);
            }
        });

        tbiayacairan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbiayacairan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbiayacairanActionPerformed(evt);
            }
        });

        tbiayatablet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbiayatablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbiayatabletActionPerformed(evt);
            }
        });

        ttanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tjumlahvisite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tjumlahvisite.setText("0");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Kunjungan");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Persalinan");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Tindakan Perawat");

        ttindakanperawat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tpersalinan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Perawatan Bayi");

        tperawatanbayi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(tbiayakamar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(tjumlahhari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(tvisitedokter, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(tjumlahvisite, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(28, 28, 28)
                        .addComponent(tperawatanbayi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(tbiayaalkes, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbiayacairan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(tbiayatablet, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpersalinan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttindakanperawat, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbiayakamar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tjumlahhari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvisitedokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tjumlahvisite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ttindakanperawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpersalinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tperawatanbayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tbiayaalkes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbiayacairan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tbiayatablet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 510, 520));

        jLabel11.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Daftar Pasien");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Form tagihan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 20));

        jLabel15.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Register");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 20));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nama Pasien");

        tnamapasien.setEditable(false);
        tnamapasien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tidpendaftaran.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tidpendaftaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tidpendaftaranKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ID Pendaftaran");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("* Form Pembayaran");

        btncaripasien.setBackground(new java.awt.Color(0, 153, 102));
        btncaripasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncaripasien.setForeground(new java.awt.Color(255, 255, 255));
        btncaripasien.setText("Cari Pasien");
        btncaripasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaripasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(54, 54, 54)
                        .addComponent(tidpendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btncaripasien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(72, 72, 72)
                        .addComponent(tnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tidpendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncaripasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 1130, 90));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FORM TAGIHAN PASIEN RAWAT INAP");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 460, 40));

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Total Tagihan");

        ttotaltagihan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Bayar");

        tbayar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbayarActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Kembalian");

        tkembalian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkembalianActionPerformed(evt);
            }
        });

        btnsimpancetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsimpancetak.setText("Simpan & Cetak");
        btnsimpancetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpancetakActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel5.setText("* Enter");

        btncetaksaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncetaksaja.setText("Cetak Saja");
        btncetaksaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetaksajaActionPerformed(evt);
            }
        });

        tbiayaambulan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbiayaambulan.setText("0");
        tbiayaambulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbiayaambulanActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Biaya Ambulan");

        tbiayapenunjang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbiayapenunjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbiayapenunjangActionPerformed(evt);
            }
        });
        tbiayapenunjang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbiayapenunjangKeyReleased(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Biaya Penunjang");

        tbiayaadmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbiayaadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbiayaadminActionPerformed(evt);
            }
        });
        tbiayaadmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbiayaadminKeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Biaya Admin");

        btnsimpantagihan.setBackground(new java.awt.Color(0, 153, 204));
        btnsimpantagihan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsimpantagihan.setText("Simpan Tagihan");
        btnsimpantagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpantagihanActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnsimpantagihan)
                                .addGap(5, 5, 5)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttotaltagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tbiayaambulan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbiayapenunjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(tbiayaadmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(379, 379, 379))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnsimpancetak, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncetaksaja, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbiayaambulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tbiayapenunjang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbiayaadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpantagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttotaltagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbayar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpancetak, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncetaksaja, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 600, 520));

        bg.setBackground(new java.awt.Color(0, 255, 204));
        bg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/formmenu.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 720));

        tidkamar.setForeground(new java.awt.Color(255, 255, 255));
        tidkamar.setText("kamar");
        getContentPane().add(tidkamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        ttotaltagihanbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ttotaltagihanbl.setForeground(new java.awt.Color(255, 255, 255));
        ttotaltagihanbl.setText("0");
        getContentPane().add(ttotaltagihanbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        jumlahvisitedokter();
        biayakamar();
        jumlahinjeksi();
        jumlahcairan();
        jumlahtablet();
        jumlahpenunjang();
        biayaperawatanbayi();
        biayapersalinan();
        biayatindakanperawat();

    }//GEN-LAST:event_btnhitungActionPerformed

    private void tidpendaftaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidpendaftaranKeyReleased

    }//GEN-LAST:event_tidpendaftaranKeyReleased

    private void tbiayaalkesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbiayaalkesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbiayaalkesActionPerformed

    private void tbiayacairanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbiayacairanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbiayacairanActionPerformed

    private void tbiayatabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbiayatabletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbiayatabletActionPerformed

    private void btnsimpantagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpantagihanActionPerformed

        String kamar = tbiayakamar.getText();
        String visit = tvisitedokter.getText();
        String injeksi = tbiayaalkes.getText();
        String cairan = tbiayacairan.getText();
        String tablet = tbiayatablet.getText();
        String admin = tbiayaadmin.getText();
        String hari = tjumlahhari.getText();
        String ambulan = tbiayaambulan.getText();
        String jmlvisit = tjumlahvisite.getText();
        String tindakan = ttindakanperawat.getText();
        int persalinan = Integer.parseInt(tpersalinan.getText());
        int perawatan = Integer.parseInt(tperawatanbayi.getText());

        String penunjang = tbiayapenunjang.getText();

        if (admin.length() == 0) {
            JOptionPane.showMessageDialog(null, "Data Masih Belum Lengkap !!");

        } else {
            try {
                con.createStatement().executeUpdate("insert into tbl_ridetpembayaran values("
                        + "'" + tidpendaftaran.getText() + "','" + kamar + "','" + visit + "','" + injeksi + "','" + cairan + "','" + tablet + "','" + penunjang + "','" + admin + "',"
                        + "'" + hari + "','" + ambulan + "','" + jmlvisit + "','" + tindakan + "','" + persalinan + "','" + perawatan + "')");
                JOptionPane.showMessageDialog(null, "Berhasil !!");
                tbayar.setEnabled(true);

                jumlahtotal();
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Gagal/Tagihan Sudah Disimpan !! " + e);
            }
        }
    }//GEN-LAST:event_btnsimpantagihanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        resetform();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbayarActionPerformed
        int jmltagihan = Integer.parseInt(ttotaltagihanbl.getText());
        int bayar = Integer.parseInt(tbayar.getText());
        int kembalian = bayar - jmltagihan;
        if (kembalian < 0) {
            JOptionPane.showMessageDialog(null, "Uang Masih Kurang !!");
        } else {
            tkembalian.setText(String.valueOf(kursIndonesia.format(kembalian)));
            btnsimpancetak.setEnabled(true);
        }
    }//GEN-LAST:event_tbayarActionPerformed

    private void tkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkembalianActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new daftar_pasienRI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        new register_rawatinap().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void btnsimpancetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpancetakActionPerformed
        String tanggal = ttanggal.getText();
        String total = ttotaltagihanbl.getText();
        String bayar = tbayar.getText();
        String kembalian = tkembalian.getText();

        try {
            con.createStatement().executeUpdate("insert into tbl_ripembayaran values("
                    + "'" + tidpendaftaran.getText() + "','" + tanggal + "','" + total + "','" + bayar + "','" + kembalian + "','" + user + "')");
            con.createStatement().executeUpdate("update tbl_ripelayanan set status_pasien='pulang' where id_pendaftaran='" + tidpendaftaran.getText() + "'");
            con.createStatement().executeUpdate("update tbl_rikamar set status_kamar='kosong' where id_kamar='" + tidkamar.getText() + "'");
            JOptionPane.showMessageDialog(null, "Berhasill !!");
            try {
                cetaknota();
            } catch (Exception ex) {
                Logger.getLogger(formtagihan_RI.class.getName()).log(Level.SEVERE, null, ex);
            }
            resetform();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Gagal !! " + e);
        }


    }//GEN-LAST:event_btnsimpancetakActionPerformed

    private void tbiayaadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbiayaadminActionPerformed
        btnsimpantagihan.setEnabled(true);
    }//GEN-LAST:event_tbiayaadminActionPerformed

    private void tbiayaadminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbiayaadminKeyReleased
        jumlahtotal();
        btnsimpantagihan.setEnabled(true);
    }//GEN-LAST:event_tbiayaadminKeyReleased

    private void tbiayaambulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbiayaambulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbiayaambulanActionPerformed

    private void tbiayapenunjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbiayapenunjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbiayapenunjangActionPerformed

    private void tbiayapenunjangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbiayapenunjangKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbiayapenunjangKeyReleased

    private void btncetaksajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetaksajaActionPerformed
        try {
            cetaknota();
        } catch (Exception ex) {
            Logger.getLogger(formtagihan_RI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncetaksajaActionPerformed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        tampilpasien();
    }//GEN-LAST:event_tcariKeyReleased

    private void tblpasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblpasienKeyPressed
        int i = tblpasien.getSelectedRow();
        tidpendaftaran.setText(modelpasien.getValueAt(i, 0).toString());
        tnamapasien.setText(modelpasien.getValueAt(i, 2).toString());
        formpasien.dispose();
    }//GEN-LAST:event_tblpasienKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = tblpasien.getSelectedRow();
        tidpendaftaran.setText(modelpasien.getValueAt(i, 0).toString());
        tnamapasien.setText(modelpasien.getValueAt(i, 2).toString());
        formpasien.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btncaripasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripasienActionPerformed
        formpasien.setVisible(true);
        tampilpasien();
    }//GEN-LAST:event_btncaripasienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formtagihan_RI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formtagihan_RI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formtagihan_RI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formtagihan_RI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formtagihan_RI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btncaripasien;
    private javax.swing.JButton btncetaksaja;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnsimpancetak;
    private javax.swing.JButton btnsimpantagihan;
    private javax.swing.JFrame formpasien;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField tbayar;
    private javax.swing.JTextField tbiayaadmin;
    private javax.swing.JTextField tbiayaalkes;
    private javax.swing.JTextField tbiayaambulan;
    private javax.swing.JTextField tbiayacairan;
    private javax.swing.JTextField tbiayakamar;
    private javax.swing.JTextField tbiayapenunjang;
    private javax.swing.JTextField tbiayatablet;
    private javax.swing.JTable tblpasien;
    private javax.swing.JTextField tcari;
    private javax.swing.JLabel tidkamar;
    public javax.swing.JTextField tidpendaftaran;
    private javax.swing.JLabel tjumlahhari;
    private javax.swing.JLabel tjumlahvisite;
    private javax.swing.JTextField tkembalian;
    public javax.swing.JTextField tnamapasien;
    private javax.swing.JTextField tperawatanbayi;
    private javax.swing.JTextField tpersalinan;
    private javax.swing.JTextField ttanggal;
    private javax.swing.JTextField ttindakanperawat;
    private javax.swing.JTextField ttotaltagihan;
    private javax.swing.JLabel ttotaltagihanbl;
    private javax.swing.JTextField tvisitedokter;
    // End of variables declaration//GEN-END:variables
 public void tanggal() {

        Calendar kal = new GregorianCalendar();
        int tahun = kal.get(Calendar.YEAR);
        int bulan = kal.get(Calendar.MONTH) + 1;
        int hari = kal.get(Calendar.DAY_OF_MONTH);

        if (bulan < 10) {
            String tanggal = tahun + "-0" + bulan + "-" + hari;
            ttanggal.setText(tanggal);
        } else {
            String tanggal = tahun + "-" + bulan + "-" + hari;

            ttanggal.setText(tanggal);
        }
    }

    public void jumlahinjeksi() {
        String idpendaftaran = tidpendaftaran.getText();
        String sql = "select sum(harga_totalinjeksi) from tbl_rialkes where id_pendaftaran='" + idpendaftaran + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String harga = rs.getString("sum(harga_totalinjeksi)");
                if (harga == null) {
                    tbiayaalkes.setText("0");
                } else {
                    tbiayaalkes.setText(harga);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void jumlahcairan() {
        String idpendaftaran = tidpendaftaran.getText();
        String sql = "select sum(harga_totalcairan) from tbl_ricairan where id_pendaftaran='" + idpendaftaran + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String harga = rs.getString("sum(harga_totalcairan)");
                if (harga == null) {
                    tbiayacairan.setText("0");
                } else {
                    tbiayacairan.setText(harga);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void jumlahtablet() {
        String idpendaftaran = tidpendaftaran.getText();
        String sql = "select sum(harga_totaltablet) from tbl_ritablet where id_pendaftaran='" + idpendaftaran + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String harga = rs.getString("sum(harga_totaltablet)");
                if (harga == null) {
                    tbiayatablet.setText("0");
                } else {
                    tbiayatablet.setText(harga);
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void jumlahpenunjang() {
        String idpendaftaran = tidpendaftaran.getText();
        String sql = "select sum(harga_totalpenunjang) from tbl_ripenunjang where id_pendaftaran='" + idpendaftaran + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String harga = rs.getString("sum(harga_totalpenunjang)");
                if (harga == null) {
                    tbiayapenunjang.setText("0");
                } else {
                    tbiayapenunjang.setText(harga);
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void jumlahvisitedokter() {
        String idpendaftaran = tidpendaftaran.getText();
        String sql = "select * from tbl_rivisitedokter where id_pendaftaran='" + idpendaftaran + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                int total = rs.getRow();
                if (total == 0) {
                    tjumlahvisite.setText("0");
                } else {
                    tjumlahvisite.setText(String.valueOf(total));
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void biayakamar() {

        try {
            con.createStatement().executeUpdate("update tbl_ripelayanan set tanggal_krs=now() where id_pendaftaran='" + tidpendaftaran.getText() + "'");
            jmlhari();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Gagall !!" + e);

        }
    }

    public void jmlhari() {
        String sql = "select hour(timediff(tanggal_krs,tanggal_mrs)) as jmljam from tbl_ripelayanan where id_pendaftaran='" + tidpendaftaran.getText() + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {

                int jmljam = Integer.parseInt(rs.getString("jmljam"));
                if (jmljam >= 0 && jmljam <= 31) {
                    tjumlahhari.setText("1");
                } else if (jmljam > 31 && jmljam <= 54) {
                    tjumlahhari.setText("2");
                } else if (jmljam > 54 && jmljam <= 78) {
                    tjumlahhari.setText("3");
                } else if (jmljam > 78 && jmljam <= 102) {
                    tjumlahhari.setText("4");
                } else if (jmljam > 102 && jmljam <= 126) {
                    tjumlahhari.setText("5");
                } else if (jmljam > 126) {
                    tjumlahhari.setText("6");
                }

                String sql1 = "select tbl_rikamar.harga_kamar,tbl_rikamar.visite_dokter,tbl_rikamar.id_kamar,tbl_ripelayanan.nama_kamar from tbl_ripelayanan "
                        + " inner join tbl_rikamar using(nama_kamar)"
                        + " where id_pendaftaran='" + tidpendaftaran.getText() + "'";

                try {
                    rs = con.createStatement().executeQuery(sql1);
                    while (rs.next()) {
                        String idkamar = rs.getString("id_kamar");
                        int harga = Integer.parseInt(rs.getString("harga_kamar"));
                        int visitdokter = Integer.parseInt(rs.getString("visite_dokter"));

                        int jmlvisit = Integer.parseInt(String.valueOf(tjumlahvisite.getText()));
                        int jmlhari = Integer.parseInt(String.valueOf(tjumlahhari.getText()));
                        if (jmlhari == 0) {
                            int jumlahtotal = 1 * harga;
                            int hargavisite = jmlvisit * visitdokter;

                            tvisitedokter.setText(String.valueOf(hargavisite));
                            tbiayakamar.setText(String.valueOf(jumlahtotal));
                            tidkamar.setText(idkamar);
                            jumlahvisitedokter();
                        } else {
                            int jumlahtotal = jmlhari * harga;
                            int hargavisite = jmlvisit * visitdokter;

                            tvisitedokter.setText(String.valueOf(hargavisite));
                            tbiayakamar.setText(String.valueOf(jumlahtotal));
                            tidkamar.setText(idkamar);
                            jumlahvisitedokter();
                        }
                    }
                } catch (Exception e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, "Gagall mengambil data harga kamar !!" + e);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Gagal mengambil data jumlah hari !!" + e);

        }

    }

    public void biayatindakanperawat() {
        String idpendaftaran = tidpendaftaran.getText();
        String sql = "select sum(harga_totaltindakan) from tbl_ritindakanperawat where id_pendaftaran='" + idpendaftaran + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String harga = rs.getString("sum(harga_totaltindakan)");
                if (harga == null) {
                    ttindakanperawat.setText("0");
                } else {
                    ttindakanperawat.setText(harga);
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void biayapersalinan() {
        String idpendaftaran = tidpendaftaran.getText();
        String sql = "select sum(biaya_persalinan) from tbl_ribiayapersalinan where id_pendaftaran='" + idpendaftaran + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String harga = rs.getString("sum(biaya_persalinan)");
                if (harga == null) {
                    tpersalinan.setText("0");
                } else {
                    tpersalinan.setText(harga);
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void biayaperawatanbayi() {
        String idpendaftaran = tidpendaftaran.getText();
        String sql = "select sum(harga_totalperawatan) from tbl_riperawatanbayi where id_pendaftaran='" + idpendaftaran + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String harga = rs.getString("sum(harga_totalperawatan)");
                if (harga == null) {
                    tperawatanbayi.setText("0");
                } else {
                    tperawatanbayi.setText(harga);
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void jumlahtotal() {
        int jmlkamar = Integer.parseInt(tbiayakamar.getText());
        int injeksi = Integer.parseInt(tbiayaalkes.getText());
        int cairan = Integer.parseInt(tbiayacairan.getText());
        int tablet = Integer.parseInt(tbiayatablet.getText());
        int visitdokter = Integer.parseInt(tvisitedokter.getText());
        int penunjang = Integer.parseInt(tbiayapenunjang.getText());
        int tindakan = Integer.parseInt(ttindakanperawat.getText());
        int persalinan = Integer.parseInt(tpersalinan.getText());
        int perawatan = Integer.parseInt(tperawatanbayi.getText());
        int admin = Integer.parseInt(tbiayaadmin.getText());

        int jumlahtotal = jmlkamar + injeksi + cairan + tablet + visitdokter + penunjang + tindakan + persalinan + perawatan + admin;
        ttotaltagihanbl.setText(String.valueOf(jumlahtotal));
        ttotaltagihan.setText(String.valueOf(kursIndonesia.format(jumlahtotal)));

    }

    public void resetform() {
        tbiayacairan.setText("");
        tbiayaalkes.setText("");
        tbiayakamar.setText("");
        tbiayatablet.setText("");
        tjumlahhari.setText("");
        tjumlahvisite.setText("");
        tvisitedokter.setText("");
        tbayar.setText("");
        ttotaltagihan.setText("");
        ttotaltagihanbl.setText("0");
        tkembalian.setText("");
        btnsimpantagihan.setEnabled(false);
        tbayar.setEnabled(false);
        btnsimpancetak.setEnabled(false);
    }

    public void cetaknota() throws Exception {

        String total = tidpendaftaran.getText();
        String tgl = ttanggal.getText();
        JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/laporan/notarawatinap.jrxml"));
        JRDesignQuery query = new JRDesignQuery();
        HashMap param = new HashMap();
        param.put("tanggal", tgl);
        query.setText("select tbl_ripelayanan.*,tbl_rm.nama_pasien,"
                + " tbl_ripembayaran.total_tagihan,tbl_ripembayaran.user, tbl_ridetpembayaran.*,tbl_obat.nama_obat,tbl_obat.harga_jual,"
                + " tbl_riresep.* from tbl_ripelayanan "
                + " inner join tbl_rm on tbl_rm.kode_rm=tbl_ripelayanan.no_rm "
                + " inner join tbl_ripembayaran using(id_pendaftaran)"
                + " inner join tbl_ridetpembayaran USING(id_pendaftaran)"
                + " inner join tbl_riresep USING(id_pendaftaran)"
                + " inner join tbl_obat on tbl_obat.id_obat=tbl_riresep.id_obat "
                + " where id_pendaftaran='" + tidpendaftaran.getText() + "' order by ket ASC");
        jd.setQuery(query);

        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
        JasperViewer.viewReport(jp, false);

    }

    public void tampilpasien() {
        String[] judul = {"ID Pendaftaran", "Kode RM", "Nama Pasien"};
        modelpasien = new DefaultTableModel(judul, 0);
        tblpasien.setModel(modelpasien);
        String sql = "Select tbl_rm.nama_pasien,tbl_ripelayanan.* from tbl_ripelayanan"
                + " inner join tbl_rm on tbl_rm.kode_rm=tbl_ripelayanan.no_rm"
                + " where nama_pasien like '%" + tcari.getText() + "%'";

        try {

            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String id = rs.getString("id_pendaftaran");
                String rm = rs.getString("no_rm");
                String nama = rs.getString("nama_pasien");

                String[] data = {id, rm, nama};
                modelpasien.addRow(data);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
